### ISSUE TITLE
How to custom listening address and port?

### ISSUE THREAD

**Issue by mokeyish** [mljar/mercury#106]
Mercury listen on `127.0.0.1:8000` by default. But I installed [mercury](https://github.com/mljar/mercury) on remote linux server, I can't access Mercury via `myremoteserverip:port`.

**Comment by mokeyish** [comment]
It's works. Thanks for answering.  I'm just trying out Mercury and don't want to use docker.  Maybe you should add this to docs to tell people how to custom listening address and port.

**Comment by pplonski** [comment]
Good idea. I reopen to fix the docs.

**Comment by pplonski** [comment]
BTW @mokeyish did you manage to build what you want in Mercury? Any features that you would like to see in the framework?

**Comment by mokeyish** [comment]
@pplonski  I want to share my machine learning model with web. I write a console app yesterday that takes input from console and fit into models then print the results to console, but It's only run on the terminal. 

 So I find `Mercury`.  It seems that `Mercury` takes input from widgets on web, and run juypter notebook once? Can  `Mercury` maintain a session? Since machine learning models are slow to load.

**Comment by pplonski** [comment]
Thanks @mokeyish. Sorry, `Mercury` cant maintain the session. Maybe there will be some option to compress the model? How long does it take to load?

`Mercury` has an option to output files created by notebook (make them downloadable), maybe you will found it useful (link to [docs](https://mercury-docs.readthedocs.io/en/latest/output-files/)).

**Comment by mokeyish** [comment]
it takes up to ten second  to load. Yes, `Mercury` is very cool.

**Comment by mokeyish** [comment]
Hi @pplonski ,Did your know this tool [streamlit](https://github.com/streamlit/streamlit)? It's also use pure python to build web app, It can maintain a session by `st.session_state`, a little diffcult than `Mercury` but more flexiable.

```python
import streamlit as st

if 'count' not in st.session_state:
    st.session_state.count = 0

print('#### start ####')

desc = st.text_input('desc')

st.write('The input is:', desc)

st.markdown("Hello **W**orld")

if st.button('Say hello'):
    st.session_state.count+=2
    st.write('Why hello there'+desc+str(st.session_state.count))

print('#### End ####')
```
