### ISSUE TITLE
Enhancement: Delete apps from within the user interface

### ISSUE THREAD

**Issue by jonaslandsgesell** [mljar/mercury#118]
Thank you for the great package!

Apps can currently be deleted from the command line `mercury delete app.ipynb`.

It would be nice to simply delete apps from the website via clicking on a delete button next to the individual app.

**Comment by pplonski** [comment]
@jonaslandsgesell you can delete the app in the Admin Panel. Just add `/admin` to the `Mercury` address and you will get Admin Panel for all objects stored in the database in the `Mercury`.  Please check the details in the docs https://mercury-docs.readthedocs.io/en/latest/admin-panel/

Please let me know if it works for you.
