### ISSUE TITLE
Enhancement: Add new apps via uploading jupyter notebooks via drag and drop in the browser

### ISSUE THREAD

**Issue by jonaslandsgesell** [mljar/mercury#119]
It would be nice, if users could create new apps via uploading their custom jupyter notebooks via drag and drop in the browser on the home screen of mercury.

Due to security concerns, this feature should only be enabled in trustworthy environments, e.g. via explicitly submitting an additional command-line argument `mercury run --enable-app-upload`.

I am curious about your thoughts.

**Comment by pplonski** [comment]
That would be a killer feature!

Some thoughts:
1. It should be available only for admin users (might be django superuser).
2. Sometimes you need to upload not only notebook but also other files: data files, `requirements.txt` - how to handle that?
3. Maybe it will be easier to specify the GitHub repo from which the notebook will be uploaded and used?
4. Maybe it will be convenient to create a Python package that will deploy the notebook. Example usage:
```py
from mercury import deploy
deploy(server="mercury-URL-or-IP-address-here", files=["my-notebook.ipynb", "requrements.txt", "data-file.csv"])
```
if user call the `deploy()` method then all files will be send to remote instance with `Mercury` server.

**Comment by pplonski** [comment]
I'm starting to work on a dashboard for managing notebooks in Mercury. It will be available in Mercury Cloud service. Users will be able to set up Mercury Server with few clicks and upload notebooks to share them.
