### ISSUE TITLE
Nothing appears on the Mercury web page（but appears admin page）.

### ISSUE THREAD

**Issue by gmoriki** [mljar/mercury#120]
Hello,everyone. 

I am contacting you to ask for your help.

Done：
`git clone https://github.com/mljar/mercury.git`
`docker-compose up --build`
There do not seem to be any errors.

And I access to localhost(or 127.0.0.1), But Nothing appears on the web page....

![image](https://user-images.githubusercontent.com/102865047/177038585-4bb3ffd8-178c-41e2-a229-2d1d1e1a2916.png)

I can access localhost/admin and login.
![image](https://user-images.githubusercontent.com/102865047/177038624-8a3c4b92-3cea-4dfc-a2d8-2449a52de342.png)

Can you please tell us what the solution is?
By the way, the HTML elements is written as follows
![image](https://user-images.githubusercontent.com/102865047/177038839-0c3e467d-0864-47c8-bd71-c6e9990aae45.png)
(example/to...??)

##.env
DEBUG=False
SERVE_STATIC=False
DJANGO_SUPERUSER_USERNAME=user
DJANGO_SUPERUSER_PASSWORD=pass
DJANGO_SUPERUSER_EMAIL=piotr@piotr.pl
SECRET_KEY="w6g9izv(!xoi(*1m!xv@w0^7%au&lu+j_hb62(#0$-n%nasc#8"
ALLOWED_HOSTS=0.0.0.0,localhost
NOTEBOOKS_PATH=../mercury_demo_1/
TIME_ZONE=Europe/Warsaw

**Comment by pplonski** [comment]
Hi, please try 0.0.0.0 when using docker.

**Comment by gmoriki** [comment]
Thank you for your reply.
0.0.0.0 also results in a blank page as well.@MacOS

In Windows environment, I remember that it became "ERR_CONNECTION_TIMED_OUT" at home.
(I don't have it with me at the moment)

**Comment by pplonski** [comment]
Could you please send the logs from docker start? Do you have any logs or errors in web console in developers tools?

**Comment by gmoriki** [comment]
I send docker start.(Please see below;log.text)
[log.txt](https://github.com/mljar/mercury/files/9039087/log.txt)

And The following error was found in Chrome's Developer tool.
![image](https://user-images.githubusercontent.com/102865047/177147318-9b934732-4cc1-4287-84da-391dc2d89814.png)

**Comment by pplonski** [comment]
@gmoriki apologize for the problems! I was on vacation and couldn't fix that earlier. By mistake I mixed static files in Mercury, it is fixed right now and the new version `1.1.1` is available. Please let me know if it works for you.

**Comment by gmoriki** [comment]
@pplonski 
I ran it again and the screen is now visible!!🐳
Thank you so much for the fix. I am very happy to be able to continue using Mercury.

I hope you had a wonderful vacation:)

**Comment by pplonski** [comment]
Great, Im happy that it works for you. 

May I ask what are you trying to build with Mercury and how have you found it?

**Comment by gmoriki** [comment]
@pplonski 
Sorry, haven't decided what to build yet.🤐
I was looking to generalize (no code) data analysis work within my team.
Mercury is the way to go for that process!

I found how to use Mercury on this web site.
https://www.salesanalytics.co.jp/datascience/datascience089/
# I am Japanese, so it is in Japanese.

I would like to introduce Mercury's Document to Japanese people soon, because there are few articles translated in Japanese.
