### ISSUE TITLE
Running mercury for first time: erratic inputs, code not running

### ISSUE THREAD

**Issue by connorferster** [mljar/mercury#121]
Hi @pplonski (and collaborators)!

First, I want to say that I have been following Mercury for a few months now after a friend told me about it. I think this is such a great project and I would like to use it as part of my Python course in September.

I thought I would try a basic demo for myself to get a feel for how it works. After some error-prone YAML data-entry on my part, I got mercury to run my four-cell test notebook. The notebook runs fine on its own in Jupyter. I have created a gist of it here so folks can review the source: https://gist.github.com/connorferster/d63600fe7afb8772ca45d53ba4875065

I have also recorded a video of my experience trying to run the app, here (unlisted):
https://youtu.be/eyuAmDSrF6o

Below is a description of what I experienced as it is recorded in the screencast video (above).

I wanted to perform two arithmetic calculations from four numeric inputs, none of which have default values.

When I run the notebook in mercury, I am presented with my four inputs in the sidebar. However, when I entered any value into three of the inputs, no matter what I entered, the numeric box showed `100`, for about 1-2 seconds before changing to my input value. This happened no matter how many different times I tried entering new and/or different data.

After waiting a few seconds to confirm that my numeric entries were accepted by the interface, I clicked "Run". I received error messages saying some of my variables were not defined.

I then tried to enter different numeric values and the interface kept erasing my input and replacing it with the previous input. 

Please help! I would love to use mercury in my course in September (which I am setting up for currently) and I don't know what's causing these bugs. Is it a problem with the numeric input?

Thanks for any help and advice that can be offered.

Python: 3.10.4
OS: Ubuntu (pop_OS) 22.04 LTS
Browser: Firefox

**Comment by pplonski** [comment]
Hi @connorferster,

Sounds like some problem with `numeric` input. Do you know maximum allowed values for your input? Please try to add `max` parameter for each numeric. The default max value is 100.

Looks like current validation for numeric input is annoying - should be improved. Ive added issue for it #122 - I will fix it next week, I'm on holidays right now.

Do you think that YAML construction can be improved? What do you think about GUI for YAML construction inside Jupyter?

**Comment by connorferster** [comment]
Hi @pplonski,

I hear you! Enjoy your holiday :)

I just tried updating the YAML to include a `max: 10000`. This seemed to work okay for the first run, only. I could input values and then the notebook ran. However, I could not change the values. I tried both manually typing a new value and also using the +/- arrows. Both inputs reverted the new input to my first input.

**Comment by connorferster** [comment]
Hi @pplonski!

Yes, the v1.1.2 update did indeed fix one of the strange behaviours. I can easily now put any value into the numeric input and run the notebook. However, when I tried to enter new, different values for a second run, whatever values I entered would be forced/reverted back to the values I entered on the first run.

This behaviour can be seen in the second half of the YouTube video I sent earlier - that behaviour has not changed in the new update. Thoughts?

**Comment by connorferster** [comment]
And you are a True Maintainer! Thank you so much for your rapid updates. Will try it out today!

**Comment by connorferster** [comment]
Wow! It's working almost perfectly now!

There is still a small bug with numeric inputs when manually entering a value < 1:

* For values `0 < x < 1`, when you enter `0.`, and you are not fast enough entering a number after the decimal, then the validation erases the decimal.
* For values `-inf < x < 0`, when you enter `-`, the same behaviour occurs (the validation erases the `-` if you don't enter a number super-fast). Note, you can use the arrow buttons to enter a negative value without a problem.

Other than that, my test.ipynb notebook is running well. It even allows me to assign units to the input values after they have been used by mercury, which is great.

Thanks so much! I think I can start building this mini-project for the course around mercury :)

**Comment by pplonski** [comment]
Closing the issue. Please check Mercury V2, new docs https://RunMercury.com
