### ISSUE TITLE
Import class from another directory that notebook

### ISSUE THREAD

**Issue by kamiljaszczynski** [mljar/mercury#143]
Hello,
I have python project with notebooks.
Noteboks are in direcotry ./notebooks
Python classes and code are in ./twitter folder.

When i want to use classes in notebooks and use in Mercury app i have error
ModuleNotFoundError: No module named 'twitter'

I use: from twitter ....
So it look like mercury cannot access my local folder/module.

I found solution to add my code to conda modules but i need create that module but maybe is another way
to show mercury that i have local code ?

Thanks for answer.

**Comment by pplonski** [comment]
cześć @kamiljaszczynski!

I don't think it is problem with `Mercury`. You have some problem with your custom packages. 

I would move the `twitter` folder into `notebooks` (`./notebooks/twitter`) and import it from there. Remember to add `__init__.py` in the `twitter` folder.

Please let me know if it works for you. 

Is you code public? How have you found `Mercury`?

**Comment by kamiljaszczynski** [comment]
Works after moved folder to noteboks :> Thanks
I did a research on how to run a jupyter notebook on a server without any code and found mercury. 
I try to prepare some reserach tools for implementation doctorate. When i finish i publich result :)
