### ISSUE TITLE
how to deploy mercury to k8s cluster?

### ISSUE THREAD

**Issue by markqiu** [mljar/mercury#146]

**Comment by pplonski** [comment]
Hi @markqiu! I've never deployed anything on k8s. There is docker-compose available in the Mercury repository. You can check what containers are created there. It can be a starting point for Mercury on k8s. How large clusters do you need?

**Comment by markqiu** [comment]
OK, I will try it. I have a 8 nodes cluster.

**Comment by markqiu** [comment]
I found tow tools.
1. https://github.com/metal3d/katenary?ref=golangexample.com
2. kompose
Both of them can convert a docer-compose.yaml to helms or k8s deployment files.
Hope it can help.
@pplonski
