### ISSUE TITLE
Windows path output handling

### ISSUE THREAD

**Issue by tfluhr** [mljar/mercury#151]
Hi.
I'm getting errors when I try to output to a windows directory.  I can actually get the application to write to the filesystem, but mercury throws errors preventing the app from running.

Here's my relevant yaml:

```
params:

    output_dir: 
        output: dir
```

and my relevant python:

`output_dir = r'C:\tmp\output'`

Finally, error output:

```python

  File "C:\Users\tfluhr\AppData\Local\Temp/ipykernel_14616/3641552627.py", line 2
    output_dir = "C:\Users\tfluhr\Anaconda3\Lib\site-packages\mercury\media\d40481ea-0cba-4fce-925e-4ec54b9b68a6\output_106"
                                                                                                                            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

```

**Comment by pplonski** [comment]
@tfluhr thanks for reporting! Looks like a problem with Windows paths. Do you have error traceback? (it will be easier for me to locate the problem)

**Comment by tfluhr** [comment]
@pplonski 

Here are the tracebacks output by mercury in the UI.

`

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20544/1810577730.py in <module>
----> 1 referenced_works = get_citations(doi)

NameError: name 'doi' is not defined

`

`
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20544/2727333250.py in <module>
----> 1 print(referenced_works)

NameError: name 'referenced_works' is not defined

`

**Comment by pplonski** [comment]
@tfluhr thanks! One more thing, could you please run the notebook with parameter `show-code: True` and send me a screenshot with Mercury output.

**Comment by tfluhr** [comment]
@pplonski see attached

<img width="658" alt="show_code_true" src="https://user-images.githubusercontent.com/35077186/181587864-fdf501c5-2376-453c-9f0e-4ec2f39d6361.PNG">
:

**Comment by pplonski** [comment]
@tfluhr thank you! Working on it ...

**Comment by pplonski** [comment]
The problem was with Windows path. The string with `\U` was interpreted as Unicode escape. You can read mode [here](https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file). 

The fix was to add `r` at the beginning of the path in the code created by Mercury. It was one of my most favorite bug fixes! :)

The new version `1.1.5` is available.
