### ISSUE TITLE
disable download button

### ISSUE THREAD

**Issue by NSC9** [mljar/mercury#152]

**Comment by pplonski** [comment]
There is no such functionality right now. It can be added. May I ask why would you like to hide it?

**Comment by NSC9** [comment]
> There is no such functionality right now. It can be added. May I ask why would you like to hide it?

It makes my [web app](https://nsc9.github.io/) a little clunky. I want it to be simple to use and the download button is unnecessary. If someone runs my web app on mobile, I don't want them to miss-click the wrong button.

**Comment by pplonski** [comment]
Ok, it think we can add such option to hide download button.

**Comment by pplonski** [comment]
I've added `allow_download` argument in `App`. You can control whether to show or hide Download button.

Please read more in docs:
- API docs https://runmercury.com/docs/input-widgets/app/
- example code https://runmercury.com/examples/static-website-jupyter-notebook/#additional-tips

Please install newest version with:

```
pip install -U mercury
```
