### ISSUE TITLE
Set widgets values dynamically 

### ISSUE THREAD

**Issue by shinuehara** [mljar/mercury#153]
It would be nice to have a way to create input fields using data from a python variable/ API response data/ YML generated file (from a python script for example)

**Comment by pplonski** [comment]
That would be a super feature. I think it can be done in code instead YAML. The YAML will be used to define the widgets and there should be a Python API to manipulate widgets if needed.

**Comment by Gray-lab** [comment]
I just wanted to second this - I often run into situations where I would like to dynamically assign dropdown option lists from some set of data (like a csv, for example). It would be great to be able to do this.

**Comment by pplonski** [comment]
Hi @shinuehara and @Gray-lab, 

we've released Mercury V2. It is now possible to have dynamic widgets. Please check the docs: https://runmercury.com/examples/dynamic-widgets/

You can install Mercury V2 with:

```
pip install mercury
```
