### ISSUE TITLE
403 error if logged into django admin

### ISSUE THREAD

**Issue by tfluhr** [mljar/mercury#154]
Hi.

I've deployed using docker-compose.  If I log in to the django admin and then browse back to the mercury site without logging out of admin, I can not run code or clear previous runs.  A 403 is returned.

"POST /api/v1/execute/1 HTTP/1.1" 403 58 "http://mercury.library.iit.edu/app/1"

Once I affirmatively log out of admin, I can run code and/or clear previous runs again.

I don't know if this is expected behavior or not, but it took me a while to figure this out.

**Comment by pplonski** [comment]
That's might be a bug. I will check it next week (Im on holidays).

**Comment by pplonski** [comment]
Thanks @Konsilion for reporting! 

With @aplonska we are working on Mercury V2, it should be ready in February this year! With V2 you will be able to add widgets with Python code - no YAML. You will be able to cache the cell results and have dynamic widgets. The execution speed is ~ 20x faster. (we also plan to provide cloud for Mercury, for faster deployment, but it will be available ~May).

After V2 release we will come back to backlog ...

**Comment by pplonski** [comment]
I couldn't reproduce this issue with Mercury V2. The new documentation is available at [RunMercury.com](https://RunMercury.com).
