### ISSUE TITLE
Uploaded file not showing up in dir? (running Mercury locally)

### ISSUE THREAD

**Issue by MogwaiMomo** [mljar/mercury#156]
Hello - I've been trying to set up Mercury for my notebook and can't seem to get the upload-file functionality to work. The documentation mentions that any file that's uploaded through the widget will appear in the same directory as the notebook, but nothing is appearing. 

<img width="741" alt="Screen Shot 2022-08-10 at 4 42 33 PM" src="https://user-images.githubusercontent.com/1649024/184041433-5be5bab1-23d8-4183-ad11-68b1636bbeb0.png">

Here is what the (locally run) Mercury UI looks like after I drag a test file ('mushroom.csv') into the upload widget:

<img width="1011" alt="Screen Shot 2022-08-10 at 4 48 08 PM" src="https://user-images.githubusercontent.com/1649024/184042143-684d2285-888f-4763-81d2-05f26d8c7999.png">

And here is what appears after I hit 'Run':
 
<img width="958" alt="Screen Shot 2022-08-10 at 4 48 38 PM" src="https://user-images.githubusercontent.com/1649024/184042186-1cc1057a-d543-4b51-b703-293caf04795b.png">

I'd assumed that "3_mushroom.csv" should appear in my notebook's directory, but I'm not seeing it there. Maybe I should be looking elsewhere? 

I am also seeing this in the console when I open up dev mode on the page, but don't know how to interpret (or if it's even related to the problem I'm having): 

<img width="1401" alt="Screen Shot 2022-08-10 at 4 53 24 PM" src="https://user-images.githubusercontent.com/1649024/184042586-a7cd8f4f-a0d8-48cc-b7de-dc79e42874f7.png">

(I'm not very familiar with web app dev, so forgive me if I'm missing something completely obvious.)

**Comment by pplonski** [comment]
@MogwaiMomo thank you for reporting! I'm checking this right now.

**Comment by pplonski** [comment]
@MogwaiMomo, please add a celll with variables that are defined in the Mercury. In your case it will be:

#### Cell 1
```py
# all your imports ...
```

#### Cell 2
```py
upload_file = "some-example-file"
```

#### Cell 3
```py
df = pd.read_csv(upload_file)

print(df.head(25))
```

Here is my example notebook with file upload:
![image](https://user-images.githubusercontent.com/6959032/184097902-95ceb6ea-332e-4a36-a211-25cc7ed297b9.png)

Please let me know if it works for you. Good luck!

**Comment by MogwaiMomo** [comment]
Ah perfect - it worked! thank you! Defining a default value/file for the upload_file variable at the top of my code made all the difference. Thanks again for the prompt and helpful reply! :)

**Comment by pplonski** [comment]
@MogwaiMomo great that it is working!

I would like to reach more users, and make notebook sharing really easy, may I ask you a few questions:
- how have you found Mercury? 
- would you be interested in the SaaS version of Mercury?

**Comment by MogwaiMomo** [comment]
Hi @pplonski - sorry for the late reply, have been away :) In answer to your questions: 

1. So far Mercury has been great (but I've only just gotten started with it, so I'll probably have more feedback in the future if you want more). I'd say the only hiccup I've had so far was figuring out the file-upload issue. 

Ultimately my goal using Mercury is to host a simple web-app version of a topic-modelling script I run in JupyterLab, one that I can link directly to my website as a (hopefully usedful) tool for other people in my line of work to use. But as a coding hobbyist who really only uses code to clean and analyze data, I've always found making the jump from script writing to app development in Python/Django difficult/daunting. I think the last time I tried learn how to set up/use Django was back in the day when Python 2.7x was still more popular than Python 3, and I always felt like I got caught up in a maze of configuration workarounds just to set things up, let alone develop my app, lol. So when I saw Mercury it sounded like a perfect way to circumvent all that headache :)

So in answer to your question re: SaaS version of Mercury - it depends on what the SaaS end product would do, but if the main pain/job it took care of - so I don't have to - was the hosting & configuring part of web app development, so I could (in theory) just upload my notebook, adjust a few settings, maybe be customize the branding/aesthetic of the UI a bit, and publish it for others to use/run, that I definitely would be interested in!

Hope this helps!

**Comment by pplonski** [comment]
@MogwaiMomo thank you! Yes, I'm thinking about building SaaS where you just upload notebooks, select subdomain, and customize branding.

If you have problems with deployment, I'm happy to help. What is more, you can easily embed the Mercury app on any website - you can deploy the Mercury app to Heroku for example, and embed the app on your website (can be static). Here is documentation https://mercury-docs.readthedocs.io/en/latest/embedding/

**Comment by MogwaiMomo** [comment]
Awesome thank you!
