### ISSUE TITLE
Add support for pre-loading variables?

### ISSUE THREAD

**Issue by j-adamczyk** [mljar/mercury#157]
I have a following use case: deploy ML model with simple GUI with Mercury. This also seems quite popular. However, my model is quite heavy and takes a bit to load. If I want to make multiple predictions one after another, this takes majority of time. Overall, loading takes about a dozen times longer than single sample inference.

I propose to add pre-loading variables to Mercury, or even warm start a bit of arbitrary Python code. For example, user could provide a file which would contain a code that loads heavy variables, or environment variables, pulls secrets from AWS Secrets Manager etc.

Would it be possible to add such functionality? Or in any other way load something that would persist between runs of a particular notebook?

**Comment by pplonski** [comment]
I have a plan to add cache option. User will add 'cache' tag to the cell which will be executed only once. This should allow to run multiple predictions on heavy model. When it will be ready? Maybe in September.

**Comment by j-adamczyk** [comment]
@pplonski that's great, waiting for it!

**Comment by pplonski** [comment]
Hi @j-adamczyk,

I've merged Mercury V2 to main branch. The V2 allows to add widgets with Python code (no YAML support).

It should be possible to load heavy ML model only once. I will add code example this week.

You can read more about Mercury V2 at [RunMercury.com](https://RunMercury.com).

**Comment by pplonski** [comment]
Here is example on how to load large dataset only once in Mercury V2 https://runmercury.com/examples/load-large-dataset-jupyter-notebook/
