### ISSUE TITLE
Js resource access

### ISSUE THREAD

**Issue by beebeed** [mljar/mercury#159]
I am have issues in rendering ipydatagrid within your excellent mercury framework. The jupyter notebook renders the datagrid outside of mercury but when run in mercury it appears not to be able to find the .js resources.
 
I get the following errors
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to create view for 'DataGridView' from module 'ipydatagrid' with model 'DataGridModel' from module 'ipydatagrid'
TypeError: c.JupyterPhosphorPanelWidget is not a constructor
    at g._createElement (https://cdn.jsdelivr.net/npm/ipydatagrid@%5E1.1.12/dist/index.js:2:997709)
```
looking at the console I see the following
```
Failed to load resource: the server responded with a status of 404 (Not Found)
:8988/media/temp/ipydatagrid.js:1
Falling back to https://cdn.jsdelivr.net/npm/ for [ipydatagrid@^1.1.12](mailto:ipydatagrid@%5e1.1.12)
```
 
not sure how to resolve this - any suggestions?

Is it possible to make the js files static so they do not need to be downloaded?

Thanks

David

**Comment by pplonski** [comment]
Hi @beebeed!

Thanks for reporting the issue. Is `ipydatagrid` working after HTML export with `nbconvert`? 

You can try to convert the notebook:

```
jupyter nbconvert --to html my-notebook.ipynb
```

If it works, then it should work with Mercury. FYI, the `ipywidgets` are not working after `nbconvert` and can't be used with Mercury.

Your error is very similar to this one https://github.com/bloomberg/ipydatagrid/issues/231

One more thought, maybe you can use Pandas DataFrame to display values and try to add some styling https://pandas.pydata.org/docs/user_guide/style.html

**Comment by beebeed** [comment]
Thanks for your quick reply @pplonski …
… indeed it currently does not work with nbconvert. The odd think is that ipydatagrid DID work in mercury before I went on holiday but now it doesn’t-  any ideas of what might have changed?

**Comment by beebeed** [comment]
As a follow-up I noticed there was an error before hand which relates to the source maps


`DevTools failed to load source map: Could not load content for https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd-render.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
`
I have checked the browser and it allows access to the source maps - does this point to another issue?

for your info I am using this code

```
from ipydatagrid import DataGrid
import numpy as np 
import pandas as pd 

df = pd.DataFrame(data=np.random.randn(5,10))
datagrid=DataGrid(df)
datagrid
```

I am curious of what has happened since this used to work!

many thanks

**Comment by pplonski** [comment]
Hi @beebeed,

I've run your example code, this is what I got:
![image](https://user-images.githubusercontent.com/6959032/188078078-08626224-d870-44a2-9329-ea3546883130.png)

![image](https://user-images.githubusercontent.com/6959032/188078117-bdb1906c-82cd-4455-b5ee-4ca1957eb6c3.png)

I think it is the issue with `ipydatagrid`.

**Comment by beebeed** [comment]
So same as me @pplonski, it is just odd that I did get it working but not idea how that happened and no idea why it isn’t working now. Have reverted to using [itables](https://github.com/mwouts/itables). 

I guess the issue is the use of widgets? Do you plan / is it possible to incorporate widgets into the mercury framework? Think it would add great functionality.

**Comment by pplonski** [comment]
@beebeed ipywidgets will not be supported in the Mercury. It has an architecture that can't support it. Sorry!

You can try to use [voila](https://github.com/voila-dashboards/voila) - they support ipywidgets.

**Comment by pplonski** [comment]
@beebeed, may I ask what functionality you need from the grid/tables display? Is it just to display the data? or for exploration?

**Comment by gmouawad** [comment]
> df = pd.DataFrame(data=np.random.randn(5,10))
> datagrid=DataGrid(df)
> datagrid

your code is showing the below message on mercury and not displaying the table:
![image](https://github.com/mljar/mercury/assets/80507466/5b221b8b-a654-493f-8b09-831f84a1b951)

**Comment by pplonski** [comment]
@gmouawad I think there should be some display method available for data grid. If you don't find a way to display it please create a new issue.
