### ISSUE TITLE
Giving privileged access to python script running in a mercury jupyter notebook?

### ISSUE THREAD

**Issue by oidebrett** [mljar/mercury#160]
I understand the security issues with this approach but is there a way to give privileged (i.e. sudo) access to python scripts that are running via mercury?

For example, I have a need to clear up some temporary files that have been created by other processes on my server and I want to include the following in my python3 script:
```
import os

if os.path.isfile('/tmp/repl-storage.json'):
    os.remove('/tmp/repl-storage.json')
```

When i run this via mercury I get the error:
PermissionError: [Errno 1] Operation not permitted: '/tmp/repl-storage.json'

**Comment by pplonski** [comment]
Hi @oidebrett,

Right now, there is no option to run scripts as sudo. Are you able to perform the `remove` operation in the Jupyter Notebook? Please try to save the file in a different path.
