### ISSUE TITLE
Variables are deleted after execution (which does not allow to work interactively)

### ISSUE THREAD

**Issue by gdelcacho** [mljar/mercury#162]
Hi! I have programmed a Jupyter Notebook which I use for data annotation, but my organization wants more people to use it and I have considering turning it into a Mercury web app. 
The problem is that, after any execution, all variables are deleted, so I cannot perform the task, which requires several executions. In particular, my program works like that:

-I select a label (in a widget)
-I execute the script
-I update the variable which contains the data
-I select another label...

In Jupyter I have no problem, because variables are not cleant until kernel is restored or session finishes. But Mercury seems not to work like that. Is it possible to configure the environment like that, in an interactive, multi-execution way? 

Thank you very much.

**Comment by pplonski** [comment]
Hi @gdelcacho,

Such a feature is not yet implemented. Right now, you can only execute all cells once. I'm planning to add such a feature. 

Can you share your notebook? What widgets are you using?

**Comment by gdelcacho** [comment]
Thank you very much for your answer, @pplonski!! 
It is a work notebook, so I am not sure if I can share it. But I am using basically 2 widgets:
-A **select widget**: *label*
-A **checkbox widget**: *finish*.

The program is like that:
1. First I select a **label** in the **select widget**.
2. I run the script (pseudocode):
if  **"data_to_annotate"** is not a variable:
     ---------------**data_to_annotate** = list()
data_to_annotate.append(**label**)
if **finish** (**checkbox label**) is True:
 ---------------create_output_file(**data_to_annotate**)
3. I select another label and I run the script again.
4. When my annotation is over, I also select "finish" in the checkbox and run the script for last time, so an output file is generated
5. I download the output file generated in 4.

The only trouble with that flux is what I told you: **data_to_annotate** is cleant after every run.

**Comment by pplonski** [comment]
@gdelcacho thank you, I understand what you would like to achieve.

Here is my plan for this feature implementation:
- keep kernel live after execution (don't kill it),
- every execution will be on 'old' kernel (already used),
- there will be option to mark cells as `cache`; they will be executed only once,
- there should be an additional button to restart the kernel
 
In your case, you will just mark the cell with `data_to_annotate=list()` as `cache`, and it will be executed only once, and its value will be kept between executions.

I will try to prototype it in the next week.

**Comment by gdelcacho** [comment]
That would be awesome! Thank you very much again and congrats for your priceless job. I will be waiting for this feature.

**Comment by pplonski** [comment]
Hi @gdelcacho,

We released Mercury V2 this week. You should be able to create an app with your scenario. You can read more about V2 on new docs website https://RunMercury.com
