### ISSUE TITLE
Mercury does not recognize yaml header at all

### ISSUE THREAD

**Issue by christopher-hacker** [mljar/mercury#163]
New to Mercury so apologies if I'm missing something here, but I've added a header and Mercury simply does not recognize it. 

My first cell is:

```json
{
   "cell_type": "raw",
   "metadata": {},
   "source": [
    "---\n",
    "title: My notebook\n",
    "description: Notebook with plot\n",
    "show-code: false\n",
    "---\n"
   ]
  },
```

Yet I get the following when I run `mercury list`: 
`(id:2) Please provide title from /workspaces/crdc-le-referral-data/notebooks/crdc_referrals_arrests/crdc_referrals_arrests.ipynb`

What am I doing wrong? I followed the documentation exactly, as far as I can tell.

**Comment by pplonski** [comment]
Hi @christopher-hacker! At first sight all looks good. Maybe try `show-code: False` with first capital letter.

You can also try to remove parameters in the YAML and check which one is causing error.

Are you able to run Mercury with `mercury run`?

**Comment by christopher-hacker** [comment]
Mercury runs fine, I tried deleting various parameters and none seemed to fix it. Deleting it and re-pasting it did? I feel like it was probably some issue with Jupyter, idk.
