### ISSUE TITLE
How to customize the context root

### ISSUE THREAD

**Issue by mstks** [mljar/mercury#165]
First of all, thank you for developing and publishing this wonderful tool! Mercury is almost the perfect tool for my use case. However, there is one thing that is troubling me.

Normally, `mercury run` command would run app with `http://localhost:8000/`, but I want to run app with like `http://localhost:8000/myapp/`. Is there any easy way to do this?

In the case of [Streamlit](https://docs.streamlit.io/library/advanced-features/configuration), for example, the base path for the URL can be customized simply by setting `baseUrlPath = "myapp"` in the configuration file or by setting environment variable `STREAMLIT_SERVER_BASE_URL_PATH=myapp` or by adding `--server.baseUrlPath myapp` option to `streamlit run` command.

I would be very happy if Mercury could be set up in a similar way.

**Comment by pplonski** [comment]
Hi @mstks, Currently, there is no such option for `mercury run`. However, you should be able to modify the URL by changing the `nginx` configuration: https://github.com/mljar/mercury/blob/main/docker/nginx/default.conf in `docker-compose` deployments, so you get any URL on production.

May I ask you, what is your use case?
