### ISSUE TITLE
Broken Links in Documentation 

### ISSUE THREAD

**Issue by mrileysamc** [mljar/mercury#170]
There are some broken links in the documentation.

For example the "[next secion](https://mercury-docs.readthedocs.io/widgets)" link at the bottom of the [YAML Parameters](https://mercury-docs.readthedocs.io/en/latest/yaml-parameters/) page. I think maybe you just need to replace "/" with "../".

**Comment by pplonski** [comment]
@mrileysamc thanks for fixes!
