### ISSUE TITLE
page not found for notebook without YAML header

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#173]
Please check https://github.com/mljar/mercury/issues/172#issuecomment-1284801787

**Comment by crestrepod** [comment]
I have the same problem

![image](https://user-images.githubusercontent.com/82171627/198858850-e538d02a-7482-4ede-8833-d56bbaf20581.png)

**Comment by pplonski** [comment]
Thank you @crestrepod for reporting the issue. Could you please provide output logs from mercury command and your notebook?

**Comment by pplonski** [comment]
No more YAML config in Mercury V2 (released this week). Please read more on https://RunMercury.com
