### ISSUE TITLE
Dynamic choices

### ISSUE THREAD

**Issue by varontron** [mljar/mercury#174]
Is it possible to override choices, e.g., in `Select` widget?  

Use case:  user uploads file using `File` widget, choices for subsequent `Select` widgets (as well as ranges for others) are derived from file.

**Comment by pplonski** [comment]
Hi @varontron, right now it is not possible. It will be implemented in v2. We hope to speedup the whole process of computation by keeping running kernels between runs. This will allow for dynamic widgets and caching.
