### ISSUE TITLE
Web App Not Loading On huggingface.co About 2 Days Ago

### ISSUE THREAD

**Issue by NSC9** [mljar/mercury#176]
Hello. I am troubling shooting where the issue is, so it may not be this github repo's fault. A week ago, I think an update on huggingface went out and broke my web app. A moderator factory reset my web app and it worked for 3 days or so. The last two days my web app has not been loading properly.

The Github Repo for my web app is at https://github.com/NSC9/nsc9.github.io

My Huggingface Repo is https://huggingface.co/spaces/NSC9/Artificial_Calculus_Teacher

A link to the discussion about this at Huggingface is at https://huggingface.co/spaces/NSC9/Artificial_Calculus_Teacher/discussions/3

It would be nice if someone could let me know if they think this is an issue on Huggingface's end or if an update on Huggingface's API somehow made mercury obsolete? Thank you!

**Comment by pplonski** [comment]
@NSC9 thank you for reporting the issue. I'm looking at it right now.

**Comment by pplonski** [comment]
@NSC9 they changed the URL structure for apps.

#### Example

It used to be:

```
https://hf.space/embed/pplonski/deploy-mercury
```

and now it is:

```
https://pplonski-deploy-mercury.hf.space
```

I'm working on fix.

**Comment by pplonski** [comment]
@NSC9 I got a fix.

Please change your `app.py` file to:

```py
import os
from dotenv import load_dotenv
from subprocess import Popen
load_dotenv()

command = ["mercury", "run", f"0.0.0.0:{os.environ.get('PORT', 7860)}"] 
worker = Popen(command) 
worker.wait()
```

You now can share many notebooks in on HF Space (amazing!) What is more, you got a unique URL address.

I've replicated your space here: https://huggingface.co/spaces/pplonski/artificial-calculus-teacher

My app address is: https://pplonski-artificial-calculus-teacher.hf.space

If you would like to iframe notebook, then just use its ID. Example: https://pplonski-artificial-calculus-teacher.hf.space/app/1

**Comment by pplonski** [comment]
I will update the docs and remove unused builds from the source code.

**Comment by NSC9** [comment]
Thanks!

**Comment by pplonski** [comment]
Updated docs: https://mercury-docs.readthedocs.io/en/latest/deploy/hugging-face-spaces/
