### ISSUE TITLE
If the title is in Japanese, the HTML file is automatically downloaded.

### ISSUE THREAD

**Issue by taikis** [mljar/mercury#178]
Hi. Thank you for this excellent product.  
I think this problem may be a recurrence of #34, or it may not have been fixed.

##  Bug report
If the page's title is in Japanese, an HTML file is downloaded each time.  

```html

<style type="text/css">
.jp-mod-noOutputs {
    padding: 0px; 
}
.jp-mod-noInput {
  padding-top: 0px;
  padding-bottom: 0px;
}
</style>
```

The first line is a blank line.

## To Reproduce

1 Create notebook file following:  

**main.ipynb**
```
---
title: 日本語のタイトル
show-code: False
---
```

``` python
print("Test")
```

2 Run `mercury run main.ipynb 127.0.0.1:8000`  
3 Open [127.0.0.1:8000](http://127.0.0.1:8000/)
→ **an HTML file is downloaded**
4 Click `Open→` botton
→ **an HTML file is downloaded**

## Environment

- mljar-mercury 1.1.6
- Python 3.8.15

**Comment by taikis** [comment]
I have confirmed the same bug with the title in Korean.

**Comment by pplonski** [comment]
Hi @taikis, thank you for reporting. I will look into it.

**Comment by pplonski** [comment]
Cant reproduce the issue in Mercury V2. Here is a screenshot:

![image](https://user-images.githubusercontent.com/6959032/218999771-953e0aad-2b3b-4469-b6f7-b4def2074d6d.png)

Mercury V2 documentation is available at https://RunMercury.com

**Comment by pplonski** [comment]
ups, there is still an issue in Mercury V2 ...

**Comment by pplonski** [comment]
Hi @taikis,

I've fixed the bug and released a new version on PyPi. Thank you for your help in finding the issue.

Please update Mercury with:

```
pip install -U mercury
```

New documentation is at https://RunMercury.com 

Thank you!
