### ISSUE TITLE
Add delete command

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#18]
There is add command to add notebook to Mercury. Please add `delete` command to remove unwanted notebook.

**Comment by propainter** [comment]
I can look into it, though I have very little django knowledge 😅

**Comment by pplonski** [comment]
The `delete` command should have a one parameter: the notebook path.

**Comment by MarvinKweyu** [comment]
@pplonski Observed here, I can add the notebook multiple times. How would this work exactly? Would it use a timestamp?

**Comment by himanshu-hevo** [comment]
Yes, I also observed. `:` when we do watch multiple time for same notebook, it adds new entry each time

**Comment by MarvinKweyu** [comment]
@pplonski  So, `mercury add my_notebook.ipynb` adds a notebook. You run the command again, it adds the same notebook to the list and so forth. Should this be possible?  

As well, before a delete command, should we have a listing of notebooks added? This command should be similar to `add`. List those notebooks in my current directory that have been added to the web then delete a specific one. 

Feasibility? Or will this add complexity

**Comment by pplonski** [comment]
@MarvinKweyu thank you for pointing out the problem with notebook duplicates, I've added a ticket for this https://github.com/mljar/mercury/issues/36

**Comment by pplonski** [comment]
@MarvinKweyu @propainter @aplonska it is possible to delete a notebook from the Mercury.

The command is:

```
mercury delete notebook_path.ipynb
```

The changes are now in the master branch. It will go to the version `0.3.0` (probably in the end of this week). To install package with new changes:

```
pip install -q -U git+https://github.com/mljar/mercury.git@master
```

Additionally, I've added `list` command to print out all notebooks. Example:
```
mercury list
```
