### ISSUE TITLE
make clickable title

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#180]
In the main view of Mercury, please make a notebook title as a link to the notebook.

![image](https://user-images.githubusercontent.com/6959032/201899829-ace67d0c-3c66-49e6-8be7-ef48f916398a.png)

Titles should work the same as the open button.

**Comment by Tejasp2003** [comment]
Hey! pplonski i can help you out with this.

**Comment by pplonski** [comment]
Great @Tejasp2003! it is all yours!

**Comment by izam-mohammed** [comment]
is this issue solved?

**Comment by pplonski** [comment]
Hi @izam-mohammed, it is not solved.

**Comment by pplonski** [comment]
this is fixed in new Mercury V2

Here you can preview how does it look like https://runmercury.com/docs/multiple-notebooks/
