### ISSUE TITLE
Docker compose stuck at step 31/35, "Browserslist: caniuse-lite is outdated"

### ISSUE THREAD

**Issue by lechiffre** [mljar/mercury#181]
Hello,

after following the Docker example for AWS, I am stuck at 31/35 step, specifically on error _"Browserslist: caniuse-lite is outdated. Please run_". Detail higlighted below:

 => [mercury-nginx build 9/9] RUN yarn build                                                                                                                               141.7s
 => => # Creating an optimized production build...                                                                                                                               
 **=> => # Browserslist: caniuse-lite is outdated. Please run:                                                                                                                     
 => => # npx browserslist@latest --update-db                                                                                                                                     
 => => # Why you should do it regularly:                                                                                                                                         
 => => # https://github.com/browserslist/browserslist#browsers-data-updating**                                                                                                     
 => [mercury-mercury  8/14] RUN pip install psycopg2                                                                                                                        26.3s
 => [mercury-mercury  9/14] RUN if [ -z "${GITHUB_TOKEN}" ] ; then         echo "Skip Pro features installation." &&         echo "Please visit https://mljar.com/pricing f  1.4s
 => [mercury-mercury 10/14] ADD ./mercury/apps /app/mercury/apps                                                                                                             0.1s
 => [mercury-mercury 11/14] ADD ./mercury/server /app/mercury/server                                                                                                         0.1s
 => [mercury-mercury 12/14] ADD ./mercury/manage.py /app/mercury/                                                                                                            0.0s
 => [mercury-mercury 13/14] ADD ./docker /app/docker                                                                                                                         0.1s
 => [mercury-mercury 14/14] RUN chmod +x /app/docker/mercury/entrypoint.sh                                                                                                   0.7s
 => [mercury-mercury] exporting to image                                                                                                                                    42.0s
 => => exporting layers                                                                                                                                                     41.9s
 => => writing image sha256:7c456f7996c34e8b98d283301b37b8cb8a47f2f2735f6e9f87bc7a62cd184720                                                                                 0.0s
 => => naming to docker.io/library/mercury-mercury                                                                                                                           0.0s

This step won't complete the docker compose fully. What should I do? I have tried to fix it inside the docker instruction but that led me to step 33 where it got stuck on # Creating an optimized production build...  without any info about the error. 

Thanks.

JK

**Comment by pplonski** [comment]
Hi @lechiffre,

what machine type are you using? Docker can stuck if machine has too low RAM memory.

I wish there was a ready docker image for Mercury, so you can skip the building process.

**Comment by lechiffre** [comment]
Got it, thanks for the answer! I was running it on the EC2 Micro instance with 1GB of memory. Never found the minimum requirement. What is the min. requirement? Thanks a lot.

**Comment by pplonski** [comment]
With 2GB should be fine.

**Comment by lechiffre** [comment]
Ok, will try to spin-off the new instance and will let you how it went.  Thanks.

**Comment by pplonski** [comment]
With @aplonska we are working on service for Mercury deployments. It will be as easy as notebook upload.

**Comment by lechiffre** [comment]
Awesome!
Thanks
