### ISSUE TITLE
Heroku: Add multiple repos to single app

### ISSUE THREAD

**Issue by connorferster** [mljar/mercury#185]
Mercury CLI has the command `add` to add a notebook file into the server as one of the apps it can run. Is it possible to do this kind of deployment on Heroku? Say, if I wanted to have a gallery of apps created by students where each student has their own repo?

**Comment by pplonski** [comment]
Hi @connorferster,

Right now, you can add multiple notebooks to a single Mercury server. All notebooks should be in the same repo. 

We are working on a SaaS version where you can easily upload notebooks. Then each student can have her own subdomain. For example:
- student1.domain.com
- student2.domain.com
- student3.doamin.com ...

There will be a free plan that will be perfect for students' projects. ETA for the SaaS version is Q1 2023.

**Comment by connorferster** [comment]
Thanks! Where do I enter the "add" commands to configure the mercury server in Heroku?

**Comment by pplonski** [comment]
Closing the issue. 

We released Mercury V2 this week. You can read more on https://RunMercury.com

We will release Mercury Cloud soon, so you will be able to upload notebooks to serve them as web apps.
