### ISSUE TITLE
add function to stop notebook execution

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#193]
Please add function that will stop notebook execution after called.

**Comment by shreyabhadwal** [comment]
Do you want the function to kill the kernel?

**Comment by pplonski** [comment]
Hi @shreyabhadwal,

I was thinking about some exception without traceback, to skip execution of some cells.

Do you have any ideas on how it can be implemented?

**Comment by shreyabhadwal** [comment]
Do you mean something like this?
https://stackoverflow.com/a/54174184/14902088

**Comment by pplonski** [comment]
Yes, @shreyabhadwal something like this. But clean, without traceback. Do you need this feature? or would like to do PR?

I'm currently working on Mercury V2, and it should be integrated with V2 cells execution engine. You can preview ongoing work on V2 at https://RunMercury.com - it should be released soon.

You can play with it after installation `pip install mercury` - it is alpha version!

**Comment by shreyabhadwal** [comment]
@pplonski  I think I would like to try doing a PR. I am quite new to opensource though, and might need some occasional help, would that be cool?

**Comment by pplonski** [comment]
Great @shreyabhadwal! Please give me some time to push V2 code to main branch. I will let you know when ready.

**Comment by pplonski** [comment]
Please take a look at this thread https://stackoverflow.com/questions/24005221/ipython-notebook-early-exit-from-cell/56953105#56953105

This code looks good, but there should be some mechanism to catch exception in Mercury while executing cells:

```python
class StopExecution(Exception):
    def _render_traceback_(self):
        pass

raise StopExecution
```

**Comment by pplonski** [comment]
here is an example of `StopExecution` for Mercury:

```python
import os

class StopExecution(Exception):
    def _render_traceback_(self):
        if os.environ.get("RUN_MERCURY") is not None:
            return ["StopExecution"]
        pass
```

but it will need some logic in execution engine inside Mercury.

**Comment by pplonski** [comment]
I've added two things:

- custom exception `StopExecution`, just raise it, to stop cells execution,
- a function `Stop()`, it raises `StopExecution`

I will update docs and create release tomorrow.

**Comment by pplonski** [comment]
- documentation https://runmercury.com/docs/output-widgets/stop/
- example https://runmercury.com/examples/stop-cell-execution-jupyter-notebook/

@shreyabhadwal, if you would like to contribute to another issue, I can help you find something interesting.
