### ISSUE TITLE
Dynamic widget choices?

### ISSUE THREAD

**Issue by simplynail** [mljar/mercury#194]
Cześć :)
I was wondering if it would be possible to refer callable/function returning a list instead of providing a hard-coded list of choices to Drop down widget YAML definition?
Idea being to do some queries or database call in that function to create list of choices dynamically. I appreciate if code is run top to bottom then potentially the choices would be then generated after first notebook run, but this is something that can be dealt with.

Not sure if this would be already somehow supported, if not could you please describe a little how Mercury does that first RAW cell parsing with some reference to the code, maybe it is something that could be added?

**Comment by pplonski** [comment]
Cześć,

Im working on Mercury V2. It will have Python API to add widgets. It will be possible to have dynamic choices. The V2 is like ipywidgets and streamlit have a baby. Widgets will trigger execution from widget definition to the bottom, it will be super simple to cache cell execution results.

**Comment by simplynail** [comment]
Great, sounds promising, ipywidgets is actually what I'm missing in Streamlit :)

Any roadmap or estimated ETA?

**Comment by pplonski** [comment]
Should be January 2023

**Comment by simplynail** [comment]
Great, sounds promising, ipywidgets is actually what I'm missing in Streamlit :)

Any roadmap or estimated ETA? Great news, looking forward!

**Comment by ddkwing** [comment]
> Should be January 2023

Hello, is there any latest progress on V2? Eagerly looking forward to it...😄

**Comment by simplynail** [comment]
Hi @pplonski ,great to hear!
Just looking at the example it seems that the calling a function with argument taken from first widget and taking result and using as choices for second widget should be also possible with current implementation (i.e. doing some rest api call to get updated choices).
Thanks!

**Comment by pplonski** [comment]
@simplynail yes it should be possible :)
