### ISSUE TITLE
map visuals from jupyter notebook unable to be displayed in mercury?

### ISSUE THREAD

**Issue by brothertonpe** [mljar/mercury#198]
Hi,

I've recently been putting together a jupyter notebook that uses the gmaps package to display google maps with custom markers.

I wanted to deploy this in mercury - however whenever I try to do so, the code runs but the map does not display. When inspecting and checking the browser console, it seems to be struggling to call on the jupyter-maps js:

![image](https://user-images.githubusercontent.com/99335268/215746096-9f532d08-a524-4a77-b3a0-41bedc406ad7.png)

When using other map visualisation packages such as folium, I don't seem to have any trouble whatsoever. Am I missing something here? Does mercury simply not support usage of the gmaps package?

**Comment by pplonski** [comment]
Hi @brothertonpe, could you provide a minimal code sample to reproduce the issue?

**Comment by brothertonpe** [comment]
I see, in that case I will need to find an alternative,

Thanks for the quick clarification

**Comment by pplonski** [comment]
I can confirm that Mercury works well with [folium](https://github.com/python-visualization/folium):

![image](https://user-images.githubusercontent.com/6959032/215753936-9f2aa48e-451e-46d6-82e2-802793283e5d.png)
