### ISSUE TITLE
conda install will lead to 404 not found

### ISSUE THREAD

**Issue by ZaneCode6574** [mljar/mercury#199]
`conda install -c conda-forge mljar-mercury` will give me a broken env and it will always show page not found on http://127.0.0.1:8000

**Comment by pplonski** [comment]
Hi @ZaneCode6574!

Thank you for reporting the issue. Please try:

enable online connection for conda
```
conda config --set offline false
```
and

```
conda clean -all
conda clean --index-cache
conda update conda
```

BTW, there is old version of Mercury in conda ... Sorry about that. Right now I'm working on Mercury V2, it will be released this month. I will update the conda then.

All the best!

**Comment by ZaneCode6574** [comment]
Thank you for your reply!
