### ISSUE TITLE
I can't see the plotly chart in the first time.

### ISSUE THREAD

**Issue by nailcankara** [mljar/mercury#201]
I can't see the plotly chart in the first time. Even though it's on my notebook, I can't see the plotly chart in the first time. But if I run once, the graphic comes after that. But I want the graphic that appears on my notebook by default to be seen here, even if it is never run. Is there a solution?

![image](https://user-images.githubusercontent.com/53586899/217007526-3ee8fc88-f67c-4d24-9ea7-e81b597e3cc5.png)

**Comment by pplonski** [comment]
Hi @nailcankara,

We released Mercury V2 this week. The issue should be fixed. Please check https://RunMercury.com for more information.
