### ISSUE TITLE
Non-exclusive notebook output types? 

### ISSUE THREAD

**Issue by simplynail** [mljar/mercury#205]
Hi @pplonski,
As I think you're now on the process of adding API access functionality to Mercury v2 I was just wondering is it actually necessary to have notebook output type (like in v1 yaml definition "output: slides" or "output: rest api") to be just one and exclusive type? 

I mean user might want to take the same notebook code file and just make it available as: slides AND rest api AND app.
Mercury could take the notebook file and generate different endpoints (up to 3) for same ipnb file

**Comment by pplonski** [comment]
Hi @simplynail,

Great comment. Yes, the notebook output can be served as different types. 

Notebooks should be called by REST API with different outcomes:
- call notebook execution with params from URL. The notebook should be displayed as website,
- call notebook execution and get HTML or PDF file with the executed notebook,
- call notebook and get JSON response.

Switching between `slides` or `app` might be difficult because cells should have `Slide Type` set to be displayed as slide, but it is possible to switch between outputs.

**Comment by simplynail** [comment]
Hi @pplonski
just to make sure if I was understood correctly as an example below:
instead of writing yaml as:
```
title: My endpoint
description: Notebook as REST API example
slug: hello
output: rest api
```
or
```
title: My endpoint
description: Notebook as REST API example
slug: hello
output: slides
```
I'm suggesting having (see last line there):
```
title: My endpoint
description: Notebook as REST API example
slug: hello
output: rest api, slides, app
```
Then mercury could expose all following endpoints based on that declaration above:

- **rest api**
-- provide endpoint `<server-address>/run/<slug>` accepting POST requests with widget values
-- provide endpoint `<server-address>/get/id-with-some-random-string` accepting GET requests for feedback of the execution and results
- **slides**
-- provide endpoint `<server-address>/<slug>?format=slides` accepting GET requests that would take you to notebook running in slides mode (note query string after the slug)
- **app**
-- provide endpoint `<server-address>/<slug>?format=app` accepting GET requests that would take you to notebook running in app mode (and skipping all the cell tagging annotation relevant to slides)
(when running mercury app with all the notebooks added shown, the tile on the frontend could have 2 buttons "app" and "slides" that would take you to relevant view)

_(using mercury v1 yaml syntax since I'm not sure what v2 syntax for that would be since I saw your App class and I think you might have abandoned yaml in v2)_

**Comment by simplynail** [comment]
frankly speaking I'm not sure if v1 or v2 is providing something similar to what I described above - reading the documentation I was under the impression I need to provide either `app` or `slides` or `rest api` and cannot use coma to put in couple of output formats

**Comment by pplonski** [comment]
Yes, in V2 you will be able to call any notebook with REST API and pass widgets values, but it is not yet implemented.

There will be no `output` parameter in V2. If your cells have slide type in meta data then notebook is treated as presentation otherwise it is web app.

**Comment by simplynail** [comment]
@pplonski I appreciate its your design decision, just a thought there: personally I liked the option to have ability to switch between `app` and `slides` without needing to alter the cell tags on the notebook.

**Comment by pplonski** [comment]
@simplynail i'm closing the issue for now. If more users want this feature, then I will implement it.
