### ISSUE TITLE
Error when opening DataFrame & Plots demo

### ISSUE THREAD

**Issue by julian-p95** [mljar/mercury#206]
EDIT 2 : Solution using 
`%matplotlib inline
import matplotlib.pyplot as plt`

Also new environment of anaconda with `conda install matplotlib pandas jupyter scipy scikit-learn` and `pip mercury`

EDIT : I found a temporary solution, but the matplotlib graphics are still not shown : 
-new environment on anaconda
-install with **pip** or **conda** of mercury, pandas, matplotlib, conda notebook
-add this in jupyter notebook (i did it in the demo)  `from matplotlib import pyplot as plt matplotlib.use('agg')`

now the demo notebook is working , but can't see the matplotlib graph

-am i the only one whon need to use `matplotlib.use('agg)` in order to not open a buggued python gui ?
-i still have this issue when launching mercury
 `Unable to load extension: pydevd_plugins.extensions.types.pydevd_plugin_pandas_types`
`Sorry,cant automatically update the kernel name in the notebook.`

<img width="875" alt="image" src="https://user-images.githubusercontent.com/64646018/218961547-94cd6e92-399f-4ea7-867d-d86929ac4ebb.png">

I will try tomorrow on my peronal notebook :) mercury is a great project , thanks a lot , its a great tool for developers !

Hi,

**I have several errors, which anaconda environment do you recommand to use ? basic one ? which library should we install ? plotly, seaborn, conda-forge notebook etc, conda-forge matplotlib, notebook, jupyter ?** I tried to find in documentation but i didn't see sorry.

Congrats for V2, can't wait to use it. When opening the demo notebook i have the following error ; is it an error on my side ? 

It opens Python GUI, but the window is blocked. I can interact with the first widgets, it is working. But from Scatter Plot nothing is working.

When i launch notebook with run mercury i have an error : `'Unable`` to load extension: ``pydevd_plugins.extensions.types.pydevd_plugin_pandas_types'`

When i go on mercury server i also have GUI python opening and error, loading my figures.
`C:\Users\julia\anaconda3\envs\mljar\lib\site-packages\pandas\plotting\_matplotlib\core.py:386: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig = self.plt.figure(figsize=self.figsize)
<ipython-input-1-cc4762caa908>:2: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  pl.show()`

I use it on a anaconda environment with geopandas, i will try on the basic environment later today or tomorrow.

Thanks :)

![image](https://user-images.githubusercontent.com/64646018/218854858-3d783dc1-c1cb-4560-9c64-1efad5530ee8.png)

Here is the detail when I installed mercury on my anaconda  
![image](https://user-images.githubusercontent.com/64646018/218856089-a78f51ba-0216-46c1-8781-1b35ac117fa4.png)

![image](https://user-images.githubusercontent.com/64646018/218858733-ac16497d-ce9a-483d-b483-29c9bff1aed9.png)

**Comment by pplonski** [comment]
@julian-p95 is it working as expected after installing `mercury` with conda?

**Comment by julian-p95** [comment]
@pplonski No I still have the issue, I am currently trying to make it work, will let you know
which anaconda environment do you recommend to use ? new one + conda install pandas/matplotlib/jupyter and pip mercury should  be enough ?

**Comment by pplonski** [comment]
Hmm, this might be an issue with Mercury. What operating system are you using and what Python version?

**Comment by julian-p95** [comment]
Ok I made it work, i duplicated your demo notebook and tried different things in each notebooks, then run mercury and tested all notebooks

Only this works : 

`import` pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt`

**Comment by pplonski** [comment]
@julian-p95  you are right! I need to add `%matplotlib inline` in Mercury. let me fix it

**Comment by julian-p95** [comment]
Glad i could help a bit, even if it is not a lot :) Thanks for your nice project !  should i mark the topic as "Close" ?

**Comment by pplonski** [comment]
Let me fix the issue. I will automatically add this line in Mercury.

**Comment by pplonski** [comment]
OK, it should be fixed now. I missed the `inline` parameter when enabling `matplotlib`. Thank you @julian-p95 for help!
