### ISSUE TITLE
Widget values override with query string (on GET request)

### ISSUE THREAD

**Issue by simplynail** [mljar/mercury#209]
What would be great is having possibility for `app` and `slides` to have option to add widget values override as a query string i.e. `<server-address>/<slug>?**widget_1=5&widget_2=Pawel**` which would take you  specific notebook page where widget_1 has value already overridden to 5 and widget_2 value set to "Pawel" (regardless of the default value declared inside notebook).

That way users could also share links the the notebooks with specific calculation inputs already filled

**Comment by pplonski** [comment]
It will be an amazing feature! Closing as a duplicate for #166.
