### ISSUE TITLE
YAML cell is not detected

### ISSUE THREAD

**Issue by mizamae** [mljar/mercury#210]
I have setup a yamls cell (the first one) as RAW but the widgets on it are not shown.

>  title: PSFB dashboard
> 
> author: xxx
> description: yyyyyyyy
> show-code: False
> params:  
>     primary_switch:
>         label: This is select label
>         input: select
>         value: Cześć
>         choices: [Cześć, Hi, Hello]
>         multi: False
>     Fsw:
>         input: numeric 
>         label: Switching frequency [Hz]
>         value: 50000
>         min: 0
>         max: 300000
>         step: 1000

the second cell has the variables assigned a default value.

When running the notebook, no single widget appears. Am I missing anything?

thanks!!

**Comment by pplonski** [comment]
Please take a look at Mercury V2 docs at https://RunMercury.com

We no longer support YAML, widgets are added with Python.
