### ISSUE TITLE
Error during notebook initialization.

### ISSUE THREAD

**Issue by ntheol** [mljar/mercury#212]
Hello, I created a demo notebook in vscode based on the demo in this https://runmercury.com/tutorials/web-app-python-jupyter-notebook/.
Everything runs normal in vscode but when I try to run mercury I get this error :
Initialize demo.ipynb
Error during notebook initialization. the JSON object must be str, bytes or bytearray, not NotebookNode
Successfully added a notebook (id:None)

Do you know what can I do to resolve this issue?

**Comment by ntheol** [comment]
import mercury as mr # for widgets
import random # for random data generation
from matplotlib import pyplot as plt # for chart

app = mr.App(title="Hello in Mercury!", description="Samples app in Mercury")
name = mr.Text(label="What is your name?", value="Piotr")
points = mr.Slider(label="Number of points", value=75, min=50, max=100)
color = mr.Select(label="Select color", value="blue", choices=["red", "green", "blue"])

x = [random.gauss(0,1) for _ in range(points.value)]
y = [random.gauss(0,1) for _ in range(points.value)]
_ = plt.plot(x,y, '*', markersize=14, color=color.value)
_ = plt.title(f"Plot for {name.value}")

and then I run from the cmd mercury run test.ipynb inside the directory

**Comment by pplonski** [comment]
Thank you @ntheol, could you please send me JSON from `test.ipynb` file? maybe there is some bug in Mercury when parsing `ipynb` file from VSCode. I would like to reproduce issue locally.

**Comment by ntheol** [comment]
[test1.txt](https://github.com/mljar/mercury/files/10755999/test1.txt)

**Comment by pplonski** [comment]
Thank you @ntheol! I'm able to reproduce the issue locally. Looking for a fix now.

**Comment by ntheol** [comment]
@pplonski Thank you! Waiting for your response
