### ISSUE TITLE
Mercury 2.0 dependencies

### ISSUE THREAD

**Issue by traderjoemama** [mljar/mercury#214]
Hellom

When I create a fresh project using Python 3.11.1 that depends on Jupyter, my environment will include `ipykernel 6.21.2`. Then when installing mercury via `pip install mercury` version `6.21.2` gets ejected in favor of `ipykernel 6.6.0`. Is there a reason for this?

Thanks!

**Comment by pplonski** [comment]
Hi @traderjoemama,

there might be some hard coded dependency ... I will debug this.

Is it working fine with Python 3.11 with this strange downgrade?

Thank you!

**Comment by traderjoemama** [comment]
Hi Piotr,

Thanks for taking a look at this. I'm attaching two files. `pip_list.txt` is my environment with nothing but a fresh install of jupyter. `pip_list_mercury.txt` is this same environment with the additional inclusion of mercury via `pip install mercury`. As you can see, there are a few dependencies that get downgraded with the install of mercury. Namely:

`psutil                   5.9.4` => `psutil                   5.8.0`
`ipykernel                6.21.2` => `ipykernel                6.6.0`
`ipywidgets               8.0.4` => `ipywidgets               8.0.3`
`jupyter_client           8.0.3` => `jupyter_client           7.4.9`
`psutil                   5.9.4` => `psutil                   5.8.0`
`websocket-client         1.5.1` => `websocket-client         1.4.2`
[pip_list_mercury.txt](https://github.com/mljar/mercury/files/10774566/pip_list_mercury.txt)
[pip_list.txt](https://github.com/mljar/mercury/files/10774567/pip_list.txt)

**Comment by pplonski** [comment]
Thank you @traderjoemama for checking it! I've set softer requirements for packages. It shouldn't downgrade them now.
