### ISSUE TITLE
File Upload not working when using windows

### ISSUE THREAD

**Issue by Wazzledi** [mljar/mercury#220]
# Description
The file widget does not work when using windows.
Uploading a file to a file widget does not update the file.filename and file.filepath

# Verbose output

> NB 2023-02-23 22:20:48,441 Update widget code_uid=File.2.41.14.1 value=['neu 3.txt', 'FbBKgYWpnwVyvgDDBznmtE'] widget type File
> NB 2023-02-23 22:20:48,441 Get file neu 3.txt from id=FbBKgYWpnwVyvgDDBznmtE
> NB 2023-02-23 22:20:48,443 File path is C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\Lib\site-packages\mercury\uploads-temp\FbBKgYWpnwVyvgDDBznmtE\nSzrpRU3FrfXrPMWgMEWnC
> NB 2023-02-23 22:20:48,443 Execute code WidgetsManager.update("File.2.41.14.1", field="filename", new_value="neu 3.txt")
WidgetsManager.update("File.2.41.14.1", field="filepath", new_value="C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\Lib\site-packages\mercury\uploads-temp\FbBKgYWpnwVyvgDDBznmtE\nSzrpRU3FrfXrPMWgMEWnC")
> NB 2023-02-23 22:20:48,444 Update reponse [{'ename': "<class 'SyntaxError'>", 'evalue': "(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \\UXXXXXXXX escape (<ipython-input-1-6fdd68758feb>, line 2)", 'output_type': 'error', 'traceback': ['\x1b[1;36m  File \x1b[1;32m"<ipython-input-1-6fdd68758feb>"\x1b[1;36m, line \x1b[1;32m2\x1b[0m\n\x1b[1;33m    WidgetsManager.update("File.2.41.14.1", field="filepath", new_value="C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\\mercury\\uploads-temp\\FbBKgYWpnwVyvgDDBznmtE\\nSzrpRU3FrfXrPMWgMEWnC")\x1b[0m\n\x1b[1;37m                                                                        ^\x1b[0m\n\x1b[1;31mSyntaxError\x1b[0m\x1b[1;31m:\x1b[0m (unicode error) \'unicodeescape\' codec can\'t decode bytes in position 2-3: truncated \\UXXXXXXXX escape\n']}], updated=False
> NB 2023-02-23 22:20:48,445 Skip nb execution, no changes in widgets

# Error causing issue
The issue which causes the error is the path "C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\Lib\site-packages\mercury\uploads-temp\FbBKgYWpnwVyvgDDBznmtE\nSzrpRU3FrfXrPMWgMEWnC".

I assume something breaks with the encoding when something tries to parse the \U character in the path.

# Workaround
To fix this issue for my pc i edited the apps/nbworker/nb.py file.
In the "update_nb" function i added the following code after line 146

`value[1] = value[1].replace("\\", "\\\\")`

This will just replace the single backslashes by double backslashes which results in a well formed path.

# Notes
I did not test this on other operating systems so i don't know if it only breaks in windows or also on mac/linux.

I tested this on 2 different windows PCs with python 3.8 and python 3.9
For this test i downloaded the latest mercury version from pip.

Edit: formation of verbose output

**Comment by pplonski** [comment]
Thank you @Wazzledi, for reporting the issue and finding the cause. I will fix it.

What about other Mercury features? Did you like them?

**Comment by pplonski** [comment]
I've used your suggested fix, and it works on Windows/Linux machines. The new version `2.0.12` is released on PyPi, it should be soon updated on conda as well. 

I would love to hear your thoughts about Mercury.

Thank you for your help!

**Comment by Wazzledi** [comment]
Perfect! Thank you for your fast fix.

I really like the framework. We currently use it for our university project to display some analysis results.
The step from version 1 to 2 was really nice. It is easier to use the framework with the code widgets instead of using the yaml definition.
I also think that it is more beautiful and easier to use than other frameworks like voila.

**Comment by pplonski** [comment]
Thank you @Wazzledi! We are working on Mercury Cloud service right now, so it will be super easy to set up a website with notebooks online.
