### ISSUE TITLE
Ouput widget broken on windows

### ISSUE THREAD

**Issue by Wazzledi** [mljar/mercury#221]
# Description
As already described in #220 the file upload is broken on windows and does not work.

The same thing is happening with the output widget.

In the function "worker_output_dir" in the file apps/storage/storage.py we get the path of the output directory.
In windows this results in a path like: 
> NB 2023-02-23 23:20:15,651 Worker output directory: C:\Users\USERNAME\AppData\Local\Programs\Python\Python38\Lib\site-packages\mercury\media\7f3f4e40-3355-44f6-aac3-5c8c64c03bbd\output_80

When executing the code nbworker/nb.py for the widget_type "OutputDir" (line 154) the path is not parsed correctly resulting in an error.

# Workaround
Either inside nbworker/nb.py file or in the storage/storage.py file we can add the following code:

`output_dir = output_dir.replace("\\", "\\\\")`

**Comment by pplonski** [comment]
Thank you @Wazzledi! I will fix it.

**Comment by pplonski** [comment]
Fixed, new version `2.0.12` released. Thank you!
