### ISSUE TITLE
Request to upgrade celery dependency version

### ISSUE THREAD

**Issue by haoch** [mljar/mercury#222]
The current `celery` version used by `mercury` has conflict with `flask-appbuilder` and `apache airflow` because:

```
Because no versions of mercury match >2.0.10,<3.0.0
 and mercury (2.0.10) depends on celery (5.1.2), mercury (>=2.0.10,<3.0.0) requires celery (5.1.2).
And because celery (5.1.2) depends on click (>=7.0,<8.0), mercury (>=2.0.10,<3.0.0) requires click (>=7.0,<8.0).
And because apache-airflow (2.5.0) depends on flask-appbuilder (4.1.4) which depends on click (>=8,<9), mercury (>=2.0.10,<3.0.0) is incompatible with apache-airflow (2.5.0).
```

Could you pls. upgrade celery dependency version to latest stable version?

**Comment by pplonski** [comment]
Thank you @haoch for reporting the issue. I set softer requirements for `celery>=5.1.2`. The new version should be released today (I need to do few more fixes).

Did you run Mercury despite version conflicts? I'm looking for your feedback :)

**Comment by haoch** [comment]
Great thanks @pplonski for the quick fix, the conflict is resolved for now.
