### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by stametsm** [mljar/mercury#223]
Hello,

I am running mercury for the purpose of running plotly graphs. When I run up either a local server or implementation into huggingface, everything runs smoothly. 

For some reason though, after an indeterminate amount of time, the plot stops showing(though you can navigate mercury and the widgets I am using), and the ability to download html or pdf stalls forever. This happens both locally and on the huggingface space I am running mercury. When I quit the server, I get the message:

greenlet: WARNING: failed in call to Py_AddPendingCall; expect a memory leak.

Is this a problem with the interaction between mercury and plotly? I'm not exactly sure what is happening.
Running on Python 3.8.13.

**Comment by pplonski** [comment]
Hi @stametsm,

Thank you for reporting the issue. Could you please send me an example notebook or link to HF Space?
