### ISSUE TITLE
Worker is closed for computation longer than 1 minute

### ISSUE THREAD

**Issue by Benjamin3381** [mljar/mercury#228]
Hi... very cool app!

I've got a problem. It strats ok but when I try to run my app (in windows) it seems the worker loses connection and the screen freezes with the message Waiting for worker below the run button. Same problem when I try to download pdf from demo dashes.

**Comment by pplonski** [comment]
Hi @Benjamin3381,

Thank you for reporting the issue. I will need few details from you to be able to reproduce the problem. What operating system are you using? How have you installed `mercury`? Could you please run `mercury` with `--verbose` flag:

```
mercury run --verbose

# or run demo
mercury run demo --verbose
```

Please attach the verbose output. Thank you!

**Comment by Benjamin3381** [comment]
Thank you for your response. It´s Windows 10. I installed via pip install mercury in the prompt.

Not sure if this part of the output is useful.

![image](https://user-images.githubusercontent.com/128069588/225733814-682b7080-c03d-416c-bae1-71389f60219d.png)

**Comment by pplonski** [comment]
Thank you @Benjamin3381, could you please attach output from few lines above and from the beginning.

The worker is starting, but it is switched off because ping/pong timed out - I don't know why, yet ...

**Comment by olekniewiarowski** [comment]
Hi, I have the same problem when trying to run the demo in google colab

**Comment by pplonski** [comment]
Hi @olekniewiarowski,

Thank you for reporting the issue. I didn't test Mercury Server on Google Colab. However, Mercury Widgets should work in Colab.

I treat Colab as a place for developing notebooks. Then notebooks-apps should be served outside notebook IDE (Colab in this case). What do you think? What is your use case?

We are working on the Mercury Cloud service. You will be able to set up a website with a custom URL address with a few clicks. Notebook deployment will be as easy as file upload. There will be a free plan for quick tests :)

**Comment by Benjamin3381** [comment]
Hi @pplonski 

You know, It seems now it strarts and works fine. I don't have the worker problem any longer. However I am getting trouble when trying to run a Bambi Bayesian Model and plot results:

import bambi as bmb (ok)
model=bmb.Model('y~ x', df2['y', 'x']]) (ok)
results = model.fit(cores=1) (dash doesn't run when I add this line to the code )

It could be because of the number of cores?

**Comment by pplonski** [comment]
Hi @olekniewiarowski,

Thank you for logs. Maybe you have updated `pyopenssl`? I found [similar issue](https://github.com/pyca/cryptography/issues/7959). Please try to update `pyopenssl`

```
conda update pyopenssl
```

What library do you plan to use for visualizations? What requirements do you have for dashboards? Do you need authentication?

**Comment by olekniewiarowski** [comment]
Hi, now the demo starts successfully with pyopenssl 23.0.0, but I still have the "waiting for worker..." problem. The websocket is connected and the worker is queued. 

Ideally, we are seeking a modular solution so that anyone can write a notebook with any python libraries (for starters matplotlib is enough) and then add the results to an interactive dashboard -- mercury looks like a good candidate.  The purpose is mainly to document and compare results between many versions of numerical models (with visual and tabular output), and accessory documentation/annotation. And for non python users, the option to upload and arrange static text/image files would be a plus.

**Comment by pplonski** [comment]
Thank you for checking this. Could you please run the server with a verbose flag:

```
mercury run --verbose
```

and attach the output. There might still be some issues.


Sounds like a challenging project. You can access Google Drive in Python with [PyDrive2](https://github.com/iterative/PyDrive2) package, so it should work. We are working on the Mercury Cloud version - you set up the website with a few clicks, add users, and upload files, would you like to test it when ready?

**Comment by nagatushar** [comment]
I got to the bitter end of getting my mercury notebook to run on heroku but I also get a waiting for worker prompt and then just a white screen. I do thing something is disconnecting and crashing.

**Comment by pplonski** [comment]
Hi @nagatushar,

Please provide steps to reproduce or output logs, so I can fix the issue. To get logs from the server please start `mercury` with the verbose flag:

```
mercury run --verbose
```

We are working on a cloud version to make deployment easier. I hope to make it available this week.

**Comment by nagatushar** [comment]
sounds like heroku has a 30 second limit which may be why I am having issues. Is there any way around this?

**Comment by Benjamin3381** [comment]
Hi @pplonski 

 I don't have the worker problem any longer. However, when I try to execute bambi Bayesian Model the app restarts. Specifically when I run the fit line

import bambi as bmb 
model=bmb.Model('y ~ x', df2[['y', 'x']]) 
results = model.fit(chains=4,cores=1) 

I was cheking out the promp and I got this:

NB 2023-03-28 21:13:47,236 Exception when check if worker id=319 is stale
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\mercury\apps\nbworker\db.py", line 132, in is_worker_stale
    self.worker = Worker.objects.get(pk=self.worker_id)
  File "C:\Users\aargothy\AppData\Roaming\Python\Python39\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\aargothy\AppData\Roaming\Python\Python39\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
apps.ws.models.Worker.DoesNotExist: Worker matching query does not exist.

**Comment by pplonski** [comment]
Hi @nagatushar,

The 30 seconds limit sounds strange ... The Mercury Cloud should be available soon for testing. The developer version is already running at https://cloud.runmercury.com (you can create account and upload notebooks but it is developer version and I do many fixes there ...) but I will need ~2 weeks to polish it.

Alternative is docker-compose deployment on AWS, GCP or Azure.

**Comment by pplonski** [comment]
HI @Benjamin3381,

Thank you for reporting the issue. Apologize for problems! There is a bug, for long running jobs, that worker is closed after 1 minute ... not sure if this is connected with @nagatushar issue?

I will fix it! I will do my best to have fix this week @aplonska 

Thank you!

**Comment by pplonski** [comment]
I fixed the issue. When the job was long (> 1 min) there was no update about worker status. 

I will release the new version later today.

**Comment by nagatushar** [comment]
I'll review it when the app updates! I will show you what I've been up to :)

thank you

**Comment by pplonski** [comment]
Version `2.1.3` with fix just released.

**Comment by Benjamin3381** [comment]
Thak you @pplonski 

Just a last question. I dont know what happened but when I uppgraded it Igot this error:
´´´
(base) C:\Users\user>mercury --version

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\mercury.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\mercury\mercury.py", line 115, in main
    execute_from_command_line(["mercury.py", "migrate", "-v", 0])
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\core\management\commands\migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\django\db\migrations\loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration storage.0001_initial is applied before its dependency workers.0001_initial on database 'default'.
´´´

**Comment by pplonski** [comment]
You got old tables migration in database. Please run

```
mercury run clear
```
