### ISSUE TITLE
Setting MERCURY_OUTPUTDIR does not apply to OutputDir widget

### ISSUE THREAD

**Issue by mizamae** [mljar/mercury#229]
Hello,

I try to setup a specific MERCURY_OUTPUTDIR in an env file. If I read the MERCURY_OUTPUTDIR  from the environment in the settings file I can see the desired MERCURY_OUTPUTDIR path. The problem comes when I try to read it in the initialization of the class OutputDir (when the widget is instantiated). At this point, the environment variable MERCURY_OUTPUTDIR does not exist and sets up the default path.

I guess this might come from the fact that the latter is executed by the worker and it might not have the same env variables as the main process (the one that executes the settings file). 

Have any of you faced this problem?? can anyone give a solution??

**Comment by pplonski** [comment]
Hi @mizamae,

You don't need to set `MERCURY_OUTPUT` directory. It will be handled by `mercury`. 
- during development (in Jupyter Notebook) it will be local path `.`
- when running notebook as a web app, then some temporary path will be generated

Please take a look at docs with example code https://runmercury.com/docs/output-widgets/outputdir/
