### ISSUE TITLE
Django InconsistentMigrationHistory error

### ISSUE THREAD

**Issue by yanqiue** [mljar/mercury#239]
Hello, I'm very new to running Mercury, I got version one up and running (mljar-mercury), but after installing V2 - `pip install mercury`- I keep getting this error whenever I try to run mercury (whether the demo or my own notebook):

  `File "my_pyhton_file_path/site-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration notebooks.0001_initial is applied before its dependency accounts.0001_initial on database 'default'.`

Any ideas as to what I'm doing wrong and how I can fix it? 
Thanks!

**Comment by pplonski** [comment]
Hi @yanqiue, you are doing all good. Please clear old database with command

```
mercury run clear
```

It should fix the problem. The new version has a lot of new features and new tables in database, thats why the problem.
