### ISSUE TITLE
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by kboom** [mljar/mercury#241]
Hello,

Consider this set of two dependent widgets:

````
service = mr.Select(value="tfs", 
                   choices=["tfs", "mps", "token"], 
                   url_key="service",
                   label="Select service")
````

and

````
scale_unit = mr.Select(
                   choices=df.loc[df['Service'] == service.value]['ScaleUnit'].values,
                   url_key="scale_unit",
                   label="Select scale units")
````

where df is the pandas dataframe which holds two columns - "Service" and "ScaleUnit". ScaleUnits are unique. If you try to run such a dashboard and  start playing with the values of first or the second, you'll get the following error

````
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 1
----> 1 scale_unit = mr.Select(
      2                    choices=df.loc[df['Service'] == service.value]['ScaleUnit'].values,
      3                    url_key="scale_unit",
      4                    label="Select scale units")

File ~\.virtualenvs\Tools.VsoNotebooks-P9MlmGxP\lib\site-packages\mercury\widgets\select.py:19, in Select.__init__(self, value, choices, label, url_key, disabled, hidden)
     17 if WidgetsManager.widget_exists(self.code_uid):
     18     self.dropdown = WidgetsManager.get_widget(self.code_uid)
---> 19     if list(self.dropdown.options) != choices:
     20         self.dropdown.options = choices
     21         self.dropdown.value = value

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
````

**Comment by pplonski** [comment]
Thank you for reporting the issue. I will fix it tomorrow morning.

I didnt have time to write docs for url_key argument. How did you know how to use it? Just curious 

We are working on public cloud offering at https://cloud.runmercury.com and looking for alpha test users and feedback

**Comment by pplonski** [comment]
Hi @kboom,

I added casting to `list` for `choices` argument in `Select` and `MultiSelect` widget. The fix will be in the next version (should be released later today).

In the meantime, you can fix it by casting `.values` to `list()`:

```py
scale_unit = mr.Select(
                   choices=list(df.loc[df['Service'] == service.value]['ScaleUnit'].values),
                   url_key="scale_unit",
                   label="Select scale units")
```

**Comment by kboom** [comment]
> Thank you for reporting the issue. I will fix it tomorrow morning.
> 
> I didnt have time to write docs for url_key argument. How did you know how to use it? Just curious
> 
> We are working on public cloud offering at https://cloud.runmercury.com and looking for alpha test users and feedback

Simply from examining the constructor `stacktrace` from what I remember. Not sure if it is used and for what, because my urls stayed the same. But it would be **extremely** useful to encode selected widgets values into the URL so links can be shared, ideally even shortened (copy button). BTW keep up the great work!
