### ISSUE TITLE
Inefficient operation when there are multiple widgets and queried data

### ISSUE THREAD

**Issue by kboom** [mljar/mercury#243]
In many cases, data must be queried ad-hoc, and any of such queries can easily take about a minute (Kusto).
Imagine if you have two widgets, and you want use one to fill the dropdown options in the other (based on its own query, which can be executed just once). Then any change in the first widget will not only simply update the second, but also run everything below, which is the main query, even if it is unchanged (so will always provide the same result).

It would be good to introduce a "RUN" button so that changing the widgets execute all widgets rerendering (of these below) but stop at the first data cell. This way the expensive query is executed only once.

**Comment by kboom** [comment]
Ah right, there is something in the examples:
`https://github.com/mljar/mercury-examples/blob/main/load-on-click.ipynb`
It works well with that.

Perhaps it's good to mention that in the docs as well.

**Comment by pplonski** [comment]
There is an option to execute the notebook on the `Run` button click. Please take a look at the `App` class https://runmercury.com/docs/input-widgets/app/, and the `continuous_update` argument, when set to `False` execution, will be after `Run` clicked. The `Run` button executes only cells below updated widgets - it automatically detects where changes were.

The solution with a `Run query` button is ok as well.

Please update `mercury` to the newest version (`2.2.0`) the `Download` button should be at the bottom, together with the `Share` button (display app URL with params from widgets, if `url_key` is set).

![image](https://user-images.githubusercontent.com/6959032/231079777-8fb259da-c911-4209-a5f7-c949f0d54a1c.png)

Sorry, that you couldn't find these in the docs, I will update the docs and [examples](https://runmercury.com/examples/).
