### ISSUE TITLE
Changing a value of a widget placed below other widgets triggers their re-rendering if another one used of the same type

### ISSUE THREAD

**Issue by kboom** [mljar/mercury#245]
Place two widgets of the same type (dropdown) in two different cells separated by a cell which prints a message with a counter.
If the upper one value is changed, all of them are re-rendered (ok) but if the lower one is changed, it's still the case, even if it should not. I suspect it has to do with the fact that these two widgets are of same type, and there is no unique identifier or something.

**Comment by pplonski** [comment]
Please try the newest `2.2.1` version. I cant reproduce it with the following code:

![image](https://user-images.githubusercontent.com/6959032/231414203-9dff118f-50d7-454f-a727-fafd5fc17f97.png)

The app running:

![Peek 2023-04-12 11-18](https://user-images.githubusercontent.com/6959032/231414380-1bebf234-ee18-4668-9a91-476e440a6bd5.gif)

Please reopen the issue if you still have the problem. Thank you!
