### ISSUE TITLE
Range widget does not trigger updates

### ISSUE THREAD

**Issue by fryanpan** [mljar/mercury#247]
**Code to Reproduce (based on docs for [Range](https://runmercury.com/docs/input-widgets/range/))**
```
import mercury as mr

app = mr.App(title="Mercury Test", description="Testing a basic notebook")

# add range widget
your_range = mr.Range(value=[0, 1], min=0, max=10, label="", step=1)
    
# access widget value in the code
print(f"Your range starts at {your_range.value[0]} ends at {your_range.value[1]}")
```

**What Happens**
https://www.loom.com/share/bbfee7152e354865a4015ec56a2e5d40

The printed values do not update after dragging the range sliders

**Environment**

```% mercury --version
3.2.5
% uname -a
Darwin BryansMoMacbook 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:19:12 PDT 2022; root:xnu-8792.41.9~3/RELEASE_ARM64_T6020 arm64
```

**Comment by pplonski** [comment]
Thank you @fryanpan for reporting the issue and detailed steps to reproduce it. I'm checking it right now.
