### ISSUE TITLE
Network Error when deployed on Hugging Face

### ISSUE THREAD

**Issue by stametsm** [mljar/mercury#248]
I recently factory reset a build using mercury in hugging face, and I am now getting a network error. The original deployment of the build was roughly 2 months ago, and was working fine until I did a factory reset.

Network Error
Please check if you have internet connection and server is running. In case of problems, please contact administrator.

There is no errors, and says the space is running.

**Comment by pplonski** [comment]
Thank you @stametsm for reporting the issue. Is your HF Space public? Could you please send me a link to it so I can check code?

I'm also working on Mercury Cloud (similar to HF) where you can just upload files to share them as a website.

**Comment by stametsm** [comment]
Hello!

Unfortunately it is not public, however I think I figured out the problem. I tried running the space with Mercury v2.1.0, and it ended up working perfectly fine. I think it might be a problem with v2.2.0 or something else unrelated.

**Comment by pplonski** [comment]
OK. May I ask, do you still have a problem with https://github.com/mljar/mercury/issues/223?

**Comment by pplonski** [comment]
@stametsm I'm able to reproduce the `Network Error` issue with the latest version. I will fix the issue.

**Comment by pplonski** [comment]
@stametsm I've fixed the issue. You can use the latest version of `mercury` with Hugging Face Spaces.

I've added documentation on how to share Jupyter Notebooks on Hugging Face with Mercury https://runmercury.com/docs/hugging-face/
