### ISSUE TITLE
Slides are not refreshed in presentation mode

### ISSUE THREAD

**Issue by erjonhub** [mljar/mercury#252]
Hello, 

Firstly the project is great. 

I ran into an issue today. The notebook working fine yesterday, is not anymore. When trying to change the parameters, the page goes blank. Moving the arrows would go to the next slide which is updated, but not in place when changing the parameters. Any solution?

Thank you

**Comment by pplonski** [comment]
Hi @erjonhub,

Thank you! Do you have still the issue after website refresh? Could you please provide notebook with example code to reproduce the issue? Are you running notebook locally or on remote server?

**Comment by erjonhub** [comment]
[Notebook3.zip](https://github.com/mljar/mercury/files/11308531/Notebook3.zip)

I am not quite sure why. I have a nearly identical notebook in which it works perfectly. I am running it locally. 

p.s. Is there any way to delete the projects from the 1st page of http://127.0.0.1:8000/? I have trying mercury a lot and now its too crowded with different projects.

**Comment by pplonski** [comment]
Thank you!

Please try to run:

```
mercury run clear
```

it will delete all notebooks and start with fresh database (this command is working only locally).

When you start `mercury run` in the directory, it will automatically add existing notebook to the server.

**Comment by pplonski** [comment]
Hi @erjonhub, 

I was able to reproduce the problem. I will search for the fix tomorrow. I will let you know!

all the best,
Piotr

**Comment by pplonski** [comment]
Hi @erjonhub,

I've fixed the slides navigation after widget update. The new version `2.2.9` is already released in PyPi, it should be soon available in conda-forge as well.

Please let me know if it works ok for you. May I ask what is your use-case for Mercury?

**Comment by erjonhub** [comment]
Great, thank you.

I am using it for a presentation in university. I like the dynamic visuals when you try to explain a threeshold, or different approaches. 

I understand that Mercury runs the current cell that the variable changed and every cell below. That might make is slow in some applications. Is there a way that you change the selection and it affects only a cell of your choice?
