### ISSUE TITLE
Links in notebook web-app

### ISSUE THREAD

**Issue by adrianblazeusz** [mljar/mercury#254]
After clicking a few hyperlinks in a row (~4) in mercury, an error pops up with the content of Network Error
Please check if you have internet connection and server is running. In case of problems, please contact administrator.

![mr-link-bug](https://user-images.githubusercontent.com/117313800/234237082-7936a119-db56-403c-ae50-c4d6d63d78b4.gif)

**Comment by pplonski** [comment]
Fixed by moving websocket initialization to a different place. The fix is available in version `2.2.7`.
