### ISSUE TITLE
Invite Users button is not working in Site view

### ISSUE THREAD

**Issue by jcterrerof** [mljar/mercury#256]
Im getting trouble to add a user to a private site. When clicking in "Invite users" it opens a new window but nothing happens

**Comment by pplonski** [comment]
Hi @jcterrerof,

I assume you are using Mercury Cloud.  Here is an example video on how to invite users:
![invite-users](https://user-images.githubusercontent.com/6959032/234581501-11e1abdd-5e1b-4b49-8b92-d160bc98081a.gif)

There can be two situations:
- You invite user that is not registered at Mercury Cloud. In this case, an email is sent to the new user.
- You invite user that is already registered. In this case, your user will get permission to access your Site.

In the above video there is invitation to the new user without account at Mercury Cloud.

After sending invitation you should see information about invitation or about current users with access rights.

**Comment by jcterrerof** [comment]
Thanks @pplonski,

But my issue its the windows its blank after clicking in "Invite users"

**Comment by pplonski** [comment]
Have you tried to refresh the website? or maybe try to logout and then login?

What is URL address in the web browser after clicking `Invite new user`? it should be `https://cloud.runmercury.com/invite-user/<some-id-number-here>`

**Comment by jcterrerof** [comment]
im just getting [https://cloud.runmercury.com/add-users](url)

**Comment by jcterrerof** [comment]
Sorry @pplonski ! i was doing it the wrong way! thanks!

**Comment by pplonski** [comment]
@jcterrerof I see the bug right now!

`Invite users` button is not working correctly ...
![image](https://user-images.githubusercontent.com/6959032/234586894-874d736b-0dce-4cf4-b0e3-70f949dee08b.png)

**Comment by jcterrerof** [comment]
Exactly! the invitation send it its to the dashboard not to the site created

**Comment by pplonski** [comment]
Fixed! Thank you @jcterrerof for help.
