### ISSUE TITLE
Error loading packages

### ISSUE THREAD

**Issue by jcterrerof** [mljar/mercury#258]
While running the app im getting the following error:

![image](https://user-images.githubusercontent.com/115708074/234611104-70f023ec-c5b5-4613-9626-efde9d8d8dc5.png)

**Comment by pplonski** [comment]
Have you uploaded requirements.txt file with needed packages?

**Comment by jcterrerof** [comment]
no. How can i do it?

**Comment by pplonski** [comment]
Please create text file requirements.txt with needed packages, and please upload the file in the similar way as notebook to the Mercury Cloud.

**Comment by jcterrerof** [comment]
now i did it, but still getting the same error (attach its the requirements.txt file)
[requirements.txt](https://github.com/mljar/mercury/files/11335829/requirements.txt)

**Comment by pplonski** [comment]
@jcterrerof looks like you dumped full environment there ...

Based on your imports you need to add two packages:

```
pymysql
pandas
```

The `mercury` package is installed by default. 

Please let me know if it works with those two packages.

**Comment by jcterrerof** [comment]
this packages are in my python code

**Comment by pplonski** [comment]
Hi @jcterrerof,

did you manage to solve the issue with packages?

**Comment by pplonski** [comment]
Closing, if you still have problems please reopen. Thank you!
