### ISSUE TITLE
running mercury from google colab

### ISSUE THREAD

**Issue by naomiunk** [mljar/mercury#259]
How can I run merciry from google colab (without opening a local server)? Is it possible?

**Comment by pplonski** [comment]
Hi @naomiunk,

In theory it is possible. However, the Google Colab should be used as a development environment. After development, notebooks should be uploaded to the Mercury Server to serve them as web apps. The [Mercury Cloud](https://cloud.runmercury.com) is a Mercury Server available publicly.

Advantages of Mercury Cloud over Google Colab:
- it is always ON,
- you can set custom subdomain for your notebooks (and there are several domains to choose),
- you can set notebook as private and invite users to view it,
- option to download executed notebook as PDF/HTML.
