### ISSUE TITLE
Error displaying widget in databricks

### ISSUE THREAD

**Issue by Prashantramappa** [mljar/mercury#260]
![image](https://user-images.githubusercontent.com/21273520/234794091-20cf6898-474a-4521-8df2-ca85279efa4a.png)

**Comment by pplonski** [comment]
Hi @Prashantramappa,

thanks for reporting the issue. What DataBricks Runtime are you using? It should be working for Runtime > 13.0.

Right now, Mercury widgets depends on `ipywidgets`, I hope to move to plain HTML/JS implementation in the future.

What is your use case?
