### ISSUE TITLE
How to server arbitrary number notebooks at a single IP:PORT address?

### ISSUE THREAD

**Issue by lidh15** [mljar/mercury#261]
Is it possible that I put lots of notebooks in the running directory and let mercury server them at the same time and I can open different tabs as what I can do in jupyter lab?

**Comment by pplonski** [comment]
Hi @lidh15,

Yes, you can serve multiple notebooks from one directory. Yes, you can open each notebook in the separate tab (window).

Below is an example:
![multiple_notebooks](https://user-images.githubusercontent.com/6959032/235072675-2b3a15cc-1aff-4ddd-a2e0-cbb90127994c.gif)

You can run mercury at localhost with selected PORT number, by default it runs at `127.0.0.1:8000`

```
mercury run 127.0.0.1:<PORT>
```

May I ask what is your use-case for Mercury? In case any questions, I'm happy to help.
