### ISSUE TITLE
Is there OAuth2 support for the Mercury web service?

### ISSUE THREAD

**Issue by xiamubobby** [mljar/mercury#262]
Or if it is easy to integrate one from users sides hence I'm not sure Mercury is using a popular Python web server component or a self-made one.

**Comment by pplonski** [comment]
Hi @xiamubobby,

Mercury is based on Django `4.2`. It can be integrated with OAuth2 provider. What is your use case? Which provider would you like to support?

**Comment by pplonski** [comment]
I'm closing the issue. Please feel free to reopen if you need more help with this issue.
