### ISSUE TITLE
Mercury installation issue on Python 3.6

### ISSUE THREAD

**Issue by max-poltora** [mljar/mercury#267]
Hi there!
I am struggling to install the mercury package. `pip install mercury` and `pip install mljar-mercury` do not work for some reasons, while installation with conda reports, that  it is not compatible with python 3.6 version...

Below is Anaconda Prompt log.

> (base) C:\Users\user>pip install mercury
> ERROR: Could not find a version that satisfies the requirement mercury (from versions: none)
> ERROR: No matching distribution found for mercury
> 
> (base) C:\Users\user>conda install -c conda-forge mljar-mercury
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> Examining @/win-64::__win==0=0: 100%|████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.96it/s]/failed
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - mljar-mercury -> python[version='>=3.7']
> 
> Your python: python=3.6
> 
> If python is on the left-most side of the chain, that's the version you've asked for.
> When python appears to the right, that indicates that the thing on the left is somehow
> not available for the python version you are constrained to. Note that conda will not
> change your python version to a different minor version unless you explicitly specify
> that.
> 
> 
> 
> 
> (base) C:\Users\user>pip install mljar-mercury
> ERROR: Could not find a version that satisfies the requirement mljar-mercury (from versions: none)
> ERROR: No matching distribution found for mljar-mercury

**Comment by pplonski** [comment]
Could you please update Python to 3.8?

**Comment by max-poltora** [comment]
@pplonski, I have reinstalled Python to 3.10.9, and everything works now
