### ISSUE TITLE
Error when uploading file

### ISSUE THREAD

**Issue by ismaelc** [mljar/mercury#27]
I'm getting this error when uploading a file through the widget

    Forbidden: /api/v1/fp/process/

**Comment by pplonski** [comment]
Hi @ismaelc,

Thanks for reporting. I asume that you are running mercury locally with watch command?

Other widgets are working fine?

Thank you!

**Comment by ismaelc** [comment]
@pplonski Yes that's correct - running locally with watch. The error disappeared when I deleted the superuser from admin. I'm not sure if that fixed it but I will monitor to see if that happens again

**Comment by pplonski** [comment]
Good that it works. Have you manage to build the app that you want?

**Comment by ismaelc** [comment]
Sorry late reply. Yeah I'm currently building a simple text analysis app for a non-techy team in our company. Thanks for creating this library
