### ISSUE TITLE
Can I pass a query string in browser to initialize the value of an input widget

### ISSUE THREAD

**Issue by hugozhu** [mljar/mercury#271]
Have read the API document, however I can't find any way to read query string from a http request. 
It will be helpful if possible.

**Comment by pplonski** [comment]
Hi @hugozhu,

Yes, you can. Please take a look at this example on [how to set slider value in URL](https://runmercury.com/docs/input-widgets/slider/#share-widget-value-in-url).

Some of input widgets have `url_key` argument. You can pass values to widgets with URL params by setting `url_key`.

Please let me know if it works for you.

**Comment by hugozhu** [comment]
Got it, many thanks!
