### ISSUE TITLE
Create widgets in the loop

### ISSUE THREAD

**Issue by danjgale** [mljar/mercury#278]
Hi there, 

I'm currently trying to figure out a way to dynamically add in `Select` widgets based on the categorical columns of a dataframe. Basically, I am trying to plot the data for different interactions of different categorical data. However, the columns between loaded dataframes might have different categorical column names, or any number of them, and thus the `Select` widgets can vary according to whatever is in the data. 

The current approach I have is to throw everything in the a dictionary, like in the example below:

```python
import numpy as np
import mercury as mr

data = # some pandas dataframe
categorical_column_names = # list categorical columns (determined via a separate function)
widgets = {}
for i in categorical_column_names:
    categorical_levels = np.unique(data[i])
    widgets[i] = mr.Select(label=i, value=categorical_levels[0], choices=categorical_levels)
```

This runs totally fine in the notebook. However, the locally hosted mercury app doesn't render all widgets, and fails to plot the data that the widgets are used for. Any thoughts? Thanks so much for mercury!

**Comment by pplonski** [comment]
Hi @danjgale,

Thank you for reporting the issue. Right now, widgets creation in the loop is not supported. 

Do you have many widgets (more than 10)? Is it possible to manually add them? Are you able to create web app without this feature?

I would love to implement this feature, but it won't be today. Next week is very probable.

**Comment by danjgale** [comment]
Hi @pplonski, 

Thanks for getting back so quick. The idea would be to avoid manually adding widgets, and instead determine the widgets based on relevant columns of the dataframe. The overall purpose of the app is to perform exploratory visualizations of various feature datasets that could vary in columns.

Note that I've also considered testing this out with `exec()`, rather than using dictionaries, but would prefer not to given the caveats of `exec()`. 

In terms of the number of widgets, the data I'd be dealing with would typically generate 3-6 widgets. 

Thanks for your interest!

**Comment by pplonski** [comment]
Hi @danjgale,

It is possible to create widgets in the loop. You need to set `url_key` to unique value to be able to see all widgets from the loop in the sidebar. The recent changes will be available in the next release (this week, I will let you know when ready).Below is small demo.

#### Notebook
![image](https://github.com/mljar/mercury/assets/6959032/df0b793b-d86f-4b1e-89b5-d6356e099d3e)

#### Web App
![Peek 2023-05-23 10-36](https://github.com/mljar/mercury/assets/6959032/9ce87165-e040-46a8-bb46-d842427b3129)

**Comment by danjgale** [comment]
Amazing, this looks exactly what I am looking for. Thank you for the quick work implementing this, and the wonderful tool in general!

**Comment by pplonski** [comment]
Fantastic! Is it working for you? The new version `2.3.0` is already released on pip and conda. 

May I ask you for writing testimonial about Mercury for our website https://RunMercury.com? You can write it here on GitHub or send me by email piotr - a t - mljar.com Thank you!
