### ISSUE TITLE
App not running on cloud.runmercury or on huggingface

### ISSUE THREAD

**Issue by erjonhub** [mljar/mercury#280]
I am not sure this is a mercury problem. My app runs perfectly in jupyter and also in mercury when running locally. Followed instructions for uploading it to huggingface but also in cloud.runmercury. The result is the same, a name error for a function that is already defined:

NameError                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 evaluation_score_output, evaluation_counts_output = evaluate_models(input_model)
      3 # check if the model has already been evaluated and if not, append the results to the dataframe
      5 evaluation_score_df = pd.concat([evaluation_score_output, evaluation_score_df], ignore_index=True)    

NameError: name 'evaluate_models' is not defined

I have triple checked and as I said, in jupyter runs smoothly

**Comment by pplonski** [comment]
Hi @erjonhub, good that it is working! Are you happy with your web app created with `mercury`?

**Comment by erjonhub** [comment]
Sorry, just saw the question. Love it! 

I was going to suggest to not load the notebook until pressing the button, but I saw the discussion already existing and I can see the issues if implemented.
