### ISSUE TITLE
Output file not displayed when there is File Input widget

### ISSUE THREAD

**Issue by kuanmy** [mljar/mercury#282]
Hi! I'm developing an app using Mercury where users can upload files, then the program will perform some processing and produce result files that allow the user to download. 

However, although the output files are created in my local correctly in the `media` folder, they aren't being displayed on the app's `Output Files` tab. After some debugging, the cause seems to be the File Input widget.

For example, the files are displayed correctly only if I comment out the `mr.File` line below:
```
import mercury as mr

# add file upload widget
my_file = mr.File(label="File upload", max_file_size="100MB")
 
# get output directory widget
my_dir = mr.OutputDir()
 
# print output directory path
print(f"All files will be saved to {my_dir.path}")
 
# save example file
import os
with open(os.path.join(my_dir.path, "example-file.txt"), "w") as fout:
    fout.write("Hello!")
```

**Comment by pplonski** [comment]
Hi @kuanmy,

Thank you for reporting the issue and code to reproduce the problem. I will look into it on Monday.

**Comment by pplonski** [comment]
I can reproduce the issue locally, working on fix.
