### ISSUE TITLE
Add equivalent of `.clicked` to Select and Text fields

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#287]
The `.clicked` event in buttons is super handy:
https://runmercury.com/examples/load-on-click/#notebook

Could you add a parameter like that to `Select`s? That way, you will no if the Select was modified on the latest iteration.
Use case: a select will modify the values of some input text fields, but you only want to modify those values if the Select was changed (otherwise you may overwrite the most recent user input for those text fields)

An equivalent would also be good for text fields - to see if the text field was modified in the most recent run.

These features would greatly improve the ability for data validation, etc, via the UI

**Comment by pplonski** [comment]
Thank you @kapily for reporting this issue. I need some time to think about it.

**Comment by pplonski** [comment]
I'm closing the issue. You can track if there was an update with some additional variable. Example:

```python
import mercury as mr
```
```python
selection = ""
```
```python
letter = mr.Select(label="Select letter", choices=["a", "b", "c"], value="a")
```
```python
if letter.value != selection:
    print("there was change")
    selection = letter.value
```
