### ISSUE TITLE
An issue for text input

### ISSUE THREAD

**Issue by nuhyurduseven** [mljar/mercury#29]
There is a problem with text input. It does not accept some symbols such as =, ?, >, ! etc. Can you change the character map for the text widget? I have to use these symbols.

**Comment by pplonski** [comment]
@nuhyurduseven it works like that on purpose. The text input is injected into the code. I sanitize a lot of characters from original text input.

But I think I can add yours characters.

**Comment by pplonski** [comment]
@nuhyurduseven you are right. It is sanitized on frontend and additionally sanitized (with the same regex) on the backend.

**Comment by pplonski** [comment]
Added required characters. Please install mercury from the GitHub to have the fix.
