### ISSUE TITLE
Add a method to determine if rendering in Mercury

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#292]
Could you add a method into the mercury library to indicate if the current execution is being done in Mercury (ie. nbconvert) instead of Jupyter? This could be useful if there is some extra code that you only want to run when the page is being rendered, but not in Jupyter. 

Maybe something like:

```
import mercury as mr
mr.in_renderer()
```

**Comment by pplonski** [comment]
Great idea! To be honest, i got a call today with one of our customers and he had method `is_mercury()`. I will add it.

**Comment by pplonski** [comment]
It will be available in version `2.3.2`.
