### ISSUE TITLE
Can you use socket.io instead of WebSocket?

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#293]
I'm trying to run mercury an environment that doesn't directly support WebSockets. Is it possible for you to use socket.io instead of WebSocket directly?

It should be relatively straightforward:
https://github.com/mljar/mercury/blob/main/frontend/src/websocket/Provider.tsx#L205

Socket: https://socket.io/

And will allow fallback to long polling or other means.

**Comment by pplonski** [comment]
Hi @kapily,

Could you provide more details about your use-case? Why WebSockets will not work and `socket.io` will work? 

By `socket.io` you mean `socket.io-client` https://github.com/socketio/socket.io-client  - beacuse you pointed only frontend code. I need more details to understand your case.

**Comment by kapily** [comment]
Oops sorry - I thought my issue was my server not supporting websockets, but turned out to be a proxy related error that I fixed. We can close this ticket, thanks!
