### ISSUE TITLE
Can you allow changing the server_url provided by clients?

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#295]
When trying to run mercury in a container behind a proxy, mercury attempts to talk to the proxy by using the `server_url` provided by the client in WSS:
https://github.com/mljar/mercury/blob/f8b0649fc20339c00c47d68b140e03f591b92805/mercury/apps/ws/tasks.py#L39

Can you instead allow for an environment variable (`FORCE_SERVER_URL` or the like) to override the URL? I just want to configure it so that my client talks to localhost. 

The current behavior might be a bug if your intention was for `MERCURY_SERVER_URL` to serve that purpose, but you forgot to read from that env variable here. 

In either case, should be like a 2-line change! Would have sent a PR, but really don't mind which way it gets implement as long as the functionality is there :)

**Comment by pplonski** [comment]
Hi @kapily,

There are two env params that are set on the frontend (I need to update docs for them):
- `REACT_APP_SERVER_URL`
- `REACT_APP_SERVER_WS`

If you set them they will propagate to the backend, they are sent in the web socket message.

**Comment by kapily** [comment]
I'm not trying to change the server url on the frontend. The frontend/end user does not need to know where or how their request gets routed. I'm trying to change it only on the backend.

**Comment by pplonski** [comment]
The frontend needs to know where is the backend. It doesn't care about proxies or routing, but you need to set up backend address in the frontend. Then, frontend will send information about the `server_url`.
