### ISSUE TITLE
Navbar scrolling off the top of the page

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#296]
When scrolling off the top of the page, the navbar comes down and covers the elements in the sidebar. 

And also when scrolling past the bottom of the page, the navbar tends to want to disappear as well (though this behavior is probably more ok than the behavior when scrolling past the top)

Some pointers:
https://stackoverflow.com/questions/37916122/how-can-i-keep-the-navbar-at-top-when-scrolling-up-past-the-top-of-the-page

Super nit, but adds some polish!

**Comment by pplonski** [comment]
Thank you @kapily for reporting the issue. Could you please provide some screenshot or screen recording with the issue? I'd love to polish it.

**Comment by kapily** [comment]
Yup - here's a screencap
![screencap3](https://github.com/mljar/mercury/assets/1063618/47e7dbcf-cd92-4a0e-94d8-fd373637afa6)

**Comment by pplonski** [comment]
Thank you. I confirm that I can reproduce the issue.

**Comment by pplonski** [comment]
I fixed the issue by setting `overscroll-behavior: none` for `html` tag. Please check docs https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

Fix will be available in version `2.3.2`.
