### ISSUE TITLE
Stop rendering if a cell encounters an error

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#302]
Can you provide a parameter to `App` to stop rendering if one of the cells encounters an error during execution?

The use case is that if you have cells depend on the execution output of previous cells, there's no point in trying to execute the rest of the cells. I think a parameter `stop_execution_on_failure` could be good, while maintaining the current default behavior.

**Comment by pplonski** [comment]
I love this idea. I will implement this feature.

**Comment by pplonski** [comment]
I added `stop_on_error` argument in the `App` widget. By default it is set to `False` which means that cells are executed even if there was an error in some cell. By setting to `True` notebook will stop execution after first error will appear.

It will be available in `2.3.2` version.
