### ISSUE TITLE
Polling `slider.value` from within a loop

### ISSUE THREAD

**Issue by hfwang132** [mljar/mercury#304]
Hello, I am new to Mercury. I would like to know if there is a way to poll the slider value from within a running loop?

Here is an example:

```python
import mercury as mr
import time

slider = mr.Slider(value=5, min=0, max=10, label="Your favourite number", step=1)

for i in range(10):
    print(f"second {i}: slider.value is {slider.value}")
    time.sleep(1)
```

My problem is, even though I have slided the slider during the running loop, the printed value won't change. Here is the output:

```
second 0: slider.value is 5
second 1: slider.value is 5
second 2: slider.value is 5
second 3: slider.value is 5
second 4: slider.value is 5
second 5: slider.value is 5
second 6: slider.value is 5
second 7: slider.value is 5
second 8: slider.value is 5
second 9: slider.value is 5
```

Using `asyncio` also avails me no desired effect:

```python
import nest_asyncio
nest_asyncio.apply()
import asyncio

async def poll():
    for i in range(10):
        print(f"second {i}: slider.value is {slider.value}")
        await asyncio.sleep(1)

asyncio.run(poll())
```

Therefore, I am writing to ask if there is a proper way to achieve this. Thanks in advance!

**Comment by pplonski** [comment]
Hi @hfwang132,

Thank you for your question. Unfortunately it is not possible. Mercury is simple framework - it is not full web framework. Because of its simplicity it has some limitations.

Mercury re-executes all cells below the updated widget. It always waits till the execution of all cells is finished.

I'd love to learn more about your use-case. Maybe we can find some workaround?

**Comment by hfwang132** [comment]
Thank you for your prompt response @pplonski . My use case is an FM radio, where I first retrieve the data using an async for loop, then process the data into audio signals, and finally play the audio. The codes look like something below:

```python
sdr = RtlSdr()
sdr.center_freq = 92_700_000 # an FM radio station running at 92.7MHz

async def main():
    async for data in sdr.stream():        
        # perform FM demodulation
        audio = fm_demodulation(data)
        # play the audio
        display(Audio(audio, autoplay=True, rate=48000, normalize=False))

asyncio.run(main())
```

The thing is, the above codes only have `sdr.center_freq` pre-adjusted to the desired value (92.7MHz). But I want to change `sdr.center_freq` in real time via a slider, so that the application looks more like an actual FM Radio receiver.

It is unfortune to hear that this is not viable. Maybe I should develop this app from a lower level. Anyway, thanks for your prompt reply! I really appreciate it.

**Comment by pplonski** [comment]
Please try other frameworks, maybe Voila will work for you?

Good luck with your app!
