### ISSUE TITLE
When you visit a URL using URL params and click Share, it appends URL parameters

### ISSUE THREAD

**Issue by kapily** [mljar/mercury#307]
When you click on the "Share" button and get the URL from a page with URLs, it appends the parameters (rather than overwriting them) and screws up the page.

![screencap3](https://github.com/mljar/mercury/assets/1063618/695941ff-08d8-43a0-93be-78c544e286a4)

Code to repro:
```
import mercury as mr
 
first_name = mr.Text(value="John", label="First Name", rows=1, url_key="first_name")
last_name = mr.Text(value="Appleseed", label="Last Name", rows=1, url_key="last_name")
animal = mr.Text(value="", label="Your favourite animal", url_key="animal")
```

**Comment by pplonski** [comment]
Good catch. Thanks for reproduction example.

**Comment by kapily** [comment]
@pplonski - have a PR here with the fix:
https://github.com/mljar/mercury/pull/308

**Comment by pplonski** [comment]
Thank you for PR!
