### ISSUE TITLE
TemplateDoesNotExist at / error 

### ISSUE THREAD

**Issue by nuhyurduseven** [mljar/mercury#31]
I got TemplateDoesNotExist at / error. Both the code in github main repo and pypi repo  have same error.  It may be related to 0.3.0 release. Can you check it out please? This is an internal server error related django.

**Comment by pplonski** [comment]
Could you please provide steps how to reproduce the issue?

**Comment by nuhyurduseven** [comment]
I am fetched and install from pypi repo and github repo main branch using command on Readme. But when I start server, I got this error. 
![resim](https://user-images.githubusercontent.com/44170620/151437358-ca2bac9c-dee4-472c-b444-3a6d6a8309d0.png)

**Comment by nuhyurduseven** [comment]
I removed all dependencies and mljar-mercury and reinstall it but unfortunately it doesn't work

**Comment by pplonski** [comment]
@nuhyurduseven what I did:

```
mkdir problem_1
cd problem_1
virtualenv venv --python=python3.8
source venv/bin/activate
pip install mljar-mercury
mercury runserver
```

I go to `http://127.0.0.1:8000` and I got server running without problems.

Could you please provide detailed steps to reproduce your bug?

**Comment by nuhyurduseven** [comment]
in wsl ubuntu, I used these command
```
sudo pip install mljar-mercury 
#or 
sudo pip install -q -U git+https://github.com/mljar/mercury.git@main
mercury runserver --runworker 
#or 
mercury watch myfile.ipnb 
```
When I check the http://127.0.0.1:8000 URL, I got the error upper.

**Comment by pplonski** [comment]
I cant reproduce your issue. Probably you have some mess with packages after updates - but it is hard to say exactly.

Could you please try to use virtual environment?

Can you try to remove the `mljar-mercury` with command:
```
sudo pip uninstall mljar-mercury
```
and then try to run a command:
```
mercury runserver
```
Does your system see the `mercury` binary?

**Comment by nuhyurduseven** [comment]
No Dr. I tried
`sudo pip uninstall mljar-mercury`
and 
`sudo pip-autoremove mljar-mercury` 

no binary mercury file I have. It doesn't work. I don't think it's related authorization in linux. 
I will try the old release. then I will inform you.

**Comment by nuhyurduseven** [comment]
The porblem is related my system in my opinion. I tried 0.2.0 release and result is same. I got same error.

**Comment by pplonski** [comment]
maybe just install conda on windows?

**Comment by nuhyurduseven** [comment]
Yes, I will switch windows side

**Comment by nuhyurduseven** [comment]
Thanks for attention.

**Comment by nuhyurduseven** [comment]
The problem is with my system. related with pip dependencies. When I use python-env, It works clearly.

**Comment by pplonski** [comment]
Great that it works!
