### ISSUE TITLE
How to achieve a cascade reaction between components

### ISSUE THREAD

**Issue by ligho** [mljar/mercury#312]
Two components, a select component and a text component, how to choose different selects, and the values ​​of the text components are displayed differently

**Comment by pplonski** [comment]
Hi @ligho,

Thank you for your question. Could you please provide more information about your use case?

Here is an example of dynamic widgets https://runmercury.com/examples/dynamic-widgets/ maybe you will find it useful.

**Comment by pplonski** [comment]
I'm closing the issue. If you will still have problems, please feel free to reopen or create a new one. Thank you!

**Comment by ligho** [comment]
Sorry for the late reply. That's not what I want. The premise of the function I want is to manually click the RUN button to execute. When I change the select component, it can automatically change the value in the text component below. When I manually click the RUN button, it can follow my current The input parameters are executed.

**Comment by ligho** [comment]
My interface has many parameters, and multiple parameters need to be changed to execute successfully, so I choose to execute manually. When it is not executed automatically, if you need to cascade two components, that is, change the value of one component, and the other component will change accordingly, which I cannot achieve.

**Comment by pplonski** [comment]
Please try to add button to trigger computation. Below is the example:

![image](https://github.com/mljar/mercury/assets/6959032/7d8ab250-ebd5-4805-8398-bf06a1aabab7)


![many-params](https://github.com/mljar/mercury/assets/6959032/4c7ed668-98f6-4904-b601-44e2bdfc0276)

**Comment by ligho** [comment]
How can I change the value of the select component and the value of the input component below it change with it?

**Comment by gmouawad** [comment]
> How can I change the value of the select component and the value of the input component below it change with it?

so to rephrase what you need: You have a select form, once you select an item from it, do you want to change the value of a text input displayed below it?

**Comment by ligho** [comment]
> > 如何改变select组件的值并且其下面的input组件的值随之改变？
> 
> 因此，重新表述您需要的内容：您有一个选择表单，一旦您从中选择了一个项目，您是否想要更改其下方显示的文本输入的值？

yes
