### ISSUE TITLE
Update select choices on the fly

### ISSUE THREAD

**Issue by gmouawad** [mljar/mercury#313]
Hello,

how can I update the choices of a select input widget on the fly after the user click on a button?
select reference: https://runmercury.com/docs/input-widgets/select/

**Comment by pplonski** [comment]
Here is an example for setting choices dynamically https://runmercury.com/examples/dynamic-widgets/

Please let me know if you need more examples.

**Comment by pplonski** [comment]
@gmouawad let me finish my coffee and I will try to provide example code for you.

**Comment by pplonski** [comment]
Example code:
- `some_api` method that takes input from `Select` and `Text` widget,
- `some_api` returns values that are used in the second `Select` widget
- `some_api` is only called on button click

Here is example code:
https://gist.github.com/pplonski/4f47dbac6068729449e89a470beef862


Running app:
![update-on-fly](https://github.com/mljar/mercury/assets/6959032/e7abc128-6d2f-4642-82af-05d7b70ddfd3)

**Comment by gmouawad** [comment]
hehe that's what I want. I was so close. thanks Piotr. my question is answered. Thank you
