### ISSUE TITLE
Notebook as REST API in Mercury V2

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#316]
The old version of Mercury (version 1) supports notebooks are REST API. Please add support for REST API in Mercury V2.

**Comment by XYyanzi** [comment]
Hi, I was wondering if there are any official plans in place to support the REST API? 🤔✨

**Comment by pplonski** [comment]
I was planning to add this, but right now I'm working on support for custom ipywidgets, and it is taking much longer than I expected.

Hard to say when it will be added.
