### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by grant-westfall** [mljar/mercury#319]
Hello! I'm new to Mercury, and I'm getting this error message when I run the following:
`dlr_selection = mr.Select(choices=df['DlrNm'].to_list(), label="Dealer choice")`
Error displaying widget: model not found

Any ideas about how I can fix this?

**Comment by pplonski** [comment]
Hi @grant-westfall,

Thank you for reporting the issue.

Please try to use the following code:
```python
dlr_selection = mr.Select(choices=list(df['DlrNm'].unique()), label="Dealer choice")
```
If you still have a problem:
- please include all code to reproduce the issue,
- please run `pip freeze` to show all packages that you have installed.

**Comment by grant-westfall** [comment]
![image](https://github.com/mljar/mercury/assets/136470142/f5fb21e8-1322-4e2d-834a-a80b6b154216)
Here's a screenshot of my code. pip freeze returned the following:

absl-py==0.11.0, aiobotocore==1.3.2, aiohttp==3.7.4.post0, aioitertools==0.7.1, alembic==1.6.5, amqp==5.1.1, anyio==3.2.1, appdirs==1.4.4, argon2-cffi==20.1.0, asgiref==3.7.2, asn1crypto==1.4.0, async-generator==1.10, async-timeout==3.0.1, attrs==21.2.0, autobahn==23.1.2, Automat==22.10.0, aws-cfn-bootstrap==2.0, azure-common==1.1.27, azure-core==1.15.0, azure-storage-blob==12.8.1, Babel==2.9.1, backcall==0.2.0, bcrypt==3.2.0, beautifulsoup4==4.12.2, billiard==3.6.4.0, bleach==3.3.0, boto3==1.26.83, botocore==1.29.152, Bottleneck==1.3.2, cached-property==1.5.2, celery==5.2.7, certifi==2021.5.30, certipy==0.1.3, cffi==1.14.5, channels==4.0.0, chardet==4.0.0, click==8.1.3, click-didyoumean==0.3.0, click-plugins==1.1.1, click-repl==0.2.0, cloudpickle==1.6.0, colorama==0.4.4, constantly==15.1.0, croniter==1.3.15, cryptography==41.0.1, cx-Oracle==8.2.1, cycler==0.10.0, daphne==4.0.0, debugpy==1.3.0, decorator==4.4.2, defusedxml==0.7.1, dj-rest-auth==3.0.0, Django==3.2.5, django-allauth==0.52.0, django-cors-headers==3.10.1, django-drf-filepond==0.4.1, django-filter==21.1, django-storages==1.13.2, djangorestframework==3.12.4, docutils==0.14, entrypoints==0.3, et-xmlfile==1.1.0, execnb==0.1.5, fastcore==1.5.29, fastjsonschema==2.17.1, fsspec==2021.6.1, future==0.18.2, gevent==22.10.2, gitdb==4.0.7, GitPython==3.1.18, greenlet==2.0.2, h2o==3.32.1.3, htmlmin==0.1.12, hyperlink==21.0.0, idna==2.10, ImageHash==4.2.0, importlib-metadata==4.5.0, importlib-resources==5.12.0, incremental==22.10.0, ipykernel==6.16.2, ipython==7.34.0

**Comment by pplonski** [comment]
OK, I see the problem. You have Python 3.7. Please update Python version to at least 3.8 version and then please update `mercury`. We support Python version 3.8 - 3.11.

**Comment by grant-westfall** [comment]
Will do! I'm working on a web app that'll allow our sales team members to easily view and understand some analysis of my team's modelling results. I came across Mercury from this article: [https://towardsdatascience.com/create-a-web-app-from-your-jupyter-notebook-with-mercury-21239b7abb37](url).

**Comment by pplonski** [comment]
Im closing the issue. If you still have a problem please reopen.
