### ISSUE TITLE
Installation error : Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools

### ISSUE THREAD

**Issue by tariqrahiman** [mljar/mercury#32]
Used pip install mljar-mercury inside an anaconda command line
Got error for psutil
Error message below

1. building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

<img width="1092" alt="2022-01-28_15-59-33" src="https://user-images.githubusercontent.com/913554/151637700-101341b4-b4ac-4676-ae38-fa727fa716aa.png">

2. I Installed C++ 14 and now i get this error
c:\program files\python310\include\pyconfig.h(200): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2

<img width="1072" alt="2022-01-28_16-38-49" src="https://user-images.githubusercontent.com/913554/151639500-550eec51-a0b0-47ce-be85-40b97d917a4c.png">

**Comment by pplonski** [comment]
@tariqrahiman thank you for reporting. What Windows version are you using? Maybe try to downgrade python to 3.8 - newer Python versions not always work on Windows.

You need to manage how to install `psutil` because it is causing error.

It is problem with your system rather with the package.

**Comment by tariqrahiman** [comment]
Thanks for the tip - i installed psutil and now I installed it correctly.
![image](https://user-images.githubusercontent.com/913554/152241994-afb9a226-c7c5-4afd-8f05-19ceb72344ca.png)

**Comment by tariqrahiman** [comment]
After installation - which prompt to initiate mercury server ? I used Anaconda environment to install. After installation i entered 
mercury runserver --runworker
mercury : The term 'mercury' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mercury runserver --runworker
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (mercury:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

![image](https://user-images.githubusercontent.com/913554/152243216-7c5d04a1-445c-426c-a8a6-2216f7a39ce5.png)

**Comment by pplonski** [comment]
Hi @tariqrahiman,

The command `mercury runserver --runworker` will start server and worker for Mercury. You should run this command in the same virtual environment as you used to install the `mljar-mercury` package.

You got the error message that the command `mercury` is unknown - that means that the package is not installed. Maybe try to switch virtual environment. From your screens I see that you have installed package in `snow` virtual env. You can try to check if the package is installed with `pip freeze`.

**Comment by pplonski** [comment]
Hi @tariqrahiman,

I got an issue with running Mercury on Windows - it might be similar to your problem https://github.com/mljar/mercury/issues/35

I will try to catch some windows laptop and debug this.
