### ISSUE TITLE
Create dynamic input widgets

### ISSUE THREAD

**Issue by gmouawad** [mljar/mercury#320]
Hello, I am trying to create a set of checkboxes based on a list of sections that might change over time
On Visual Studio if I run the cell, I am seeing the checkboxes created:
![image](https://github.com/mljar/mercury/assets/80507466/2440fb31-70eb-4f00-8f0d-bd8c4d76949c)

But on the mercury web app, it is showing randomly one checkbox:
![image](https://github.com/mljar/mercury/assets/80507466/fc38cd3a-e9a3-43c1-91b6-4946b5f782d9)

Is there a way to fulfill the above?

Thanks.

**Comment by pplonski** [comment]
Hi @gmouawad,

Please add unique `url_key` to widgets created in the loop. Here is an example https://runmercury.com/examples/create-widgets-in-loop/
