### ISSUE TITLE
Access user information in the notebook

### ISSUE THREAD

**Issue by gmouawad** [mljar/mercury#325]
Hello, I have two requirements for my mercury notebook:
1. Align widgets horizontally side by side (2 checkboxes for example)
2. How to get the user logged in to the app (mercury app)

**Comment by pplonski** [comment]
Right now, it is not possible to align widgets horizontally. All widgets are displayed one by one vertically.

Please make your Site as `PRIVATE` to force users to login before accessing notebooks.

**Comment by gmouawad** [comment]
> Right now, it is not possible to align widgets horizontally. All widgets are displayed one by one vertically.
> 
> Please make your Site as `PRIVATE` to force users to login before accessing notebooks - it can be done in Admin Panel.

dear Piotr, thanks for your answer.

for point 1, will it be included in the next releases?
for point 2, I mean, if the user is already logged in, is there a mercury function that I can use in my Python code to retrieve the username of the logged-in user to my app?

**Comment by pplonski** [comment]
1. What is your use case for horizontal widgets? Could you please provide more details? 
2. I need to implement this feature. What information would you like to access for logged user? Username and email?

**Comment by gmouawad** [comment]
> 1. What is your use case for horizontal widgets? Could you please provide more details?
> 2. I need to implement this feature. What information would you like to access for logged user? Username and email?

1. I have a notebook with multiple sections. I need to give the user a list of checkboxes to display/hide sections.
2. Any property related to the user is ok. email, username, displayname etc

**Comment by pplonski** [comment]
There will be `user()` method that will return JSON dict with `username` and `email` of current user. If user is not logged, then it is returned empty dict.

It will be available in the next release.
