### ISSUE TITLE
Server returns empty page.

### ISSUE THREAD

**Issue by doxg** [mljar/mercury#327]
Greetings! 

I am new to Mercury. So I have followed guide described at https://runmercury.com/docs/docker-compose/
It says that after running docker-compose up, I should be able to get main page at http://local-machine-ip-address
However it returns: empty HTML ERR_EMPTY_RESPONSE.
There is not error logs in terminal. 

Any help would be appreciated.

**Comment by doxg** [comment]
I apologize. I messed up with port configuration. Everything is resolved.

**Comment by pplonski** [comment]
Hi @doxg,

Great that it is working! Are you using deployment with HTTPS support? In case any questions, I'm happy to help.

May I ask what are you building with Mercury?
