### ISSUE TITLE
Forbidden: /api/v1/execute/31

### ISSUE THREAD

**Issue by iamirulofficial** [mljar/mercury#33]
Forbidden: /api/v1/execute/31
[04/Feb/2022 09:04:59] "POST /api/v1/execute/31 HTTP/1.1" 403 58

Running in GCP AI Platform, This is happening when we are editing some form value and clicking on Run,

PS : Added one extra IP in Allowed Host to run in GCP AI Platform

**Comment by pplonski** [comment]
Hi @iamirulofficial, 

Thank you for reporting the issue. What web browser are you using? Could you please try to check if the same error is happening in the different web browser or web browser in the different computer?

Are you able to see preview of your notebook?

**Comment by iamirulofficial** [comment]
Hey @pplonski : 
I have tried with Safari, Chrome my colegue tried with Firefox and Microsoft edge its happening all around , App is working and notebooks with **no input like text, numeric, select** are working fine, 

But when we are executing some notebook with inputs , running the notebooks with changed input throwing this error,

Probable reason is csrf token issue while post method csrf token is missing , Where I can find the script where this api is being hit ? (taskSlice.ts) in the distribution

<img width="1512" alt="Screenshot 2022-02-07 at 12 39 32" src="https://user-images.githubusercontent.com/47473418/152741610-4fc232cd-e8a9-4471-b6a7-3082001c1450.png">

**Comment by pplonski** [comment]
@iamirulofficial thank you for checking. That's really strange behavior.

How the app is deployed? Is it deployed with docker-compose?

I've just tried in the Chrome with the IP address and PORT from your screenshot and the POST request works but the app is still in the loading state. This might be some problem with worker.

**Comment by iamirulofficial** [comment]
@pplonski Not sure, I am struggling to find out what's happening, As I have mentioned I am running the App through GCP AI Platform with Internal IP and running through `mercury runserver <internal_ip>:1234` and it is running in external IP

**Comment by pplonski** [comment]
@iamirulofficial please try to run with the command:

```
mercury runserver <internal_ip>:1234 --runworker
```

**Comment by iamirulofficial** [comment]
@pplonski Sure I will try and let you know
