### ISSUE TITLE
Dash ag grid stop working after including a js in mercury docker

### ISSUE THREAD

**Issue by gmouawad** [mljar/mercury#334]
Hello,

I have mercury installed as docker container.
I implemented a jupyter notebook using the dash ag grid table. It was working fine.

After adding a folder called /assets under /app/mercury and including a js file there to be able to filter a date column, the Grid is not rendering anymore and I am getting the below error:

![image](https://github.com/mljar/mercury/assets/80507466/50f8fe33-083f-4b96-b683-198a0dd0b7d4)

**Comment by pplonski** [comment]
Thank you for reporting. Could you please provide link to dash ag grid package?

**Comment by gmouawad** [comment]
> Thank you for reporting. Could you please provide link to dash ag grid package?

sure, [Dash AG Grid](https://dash.plotly.com/dash-ag-grid)

**Comment by gmouawad** [comment]
Hello @pplonski any update on this issue?

**Comment by pplonski** [comment]
Sorry, i didnt have time to look into it.

**Comment by pplonski** [comment]
Hi @gmouawad,

You mean error that port is already in use? It means that you are running some web app at this port. It shouldn't be related. 

I was thinking about your use case ... I remember that you tell me that you are looking for a table that can be used for data display and have search option. I was experimenting with Data Tables js package https://datatables.net/ and I'm thinking about integration of it with Mercury. It has option to search through data in the table. But it is doing search globally on all columns. Do you need search per column?

Data Tables has option to sort data and display it with pagination. I would love to add option to add option to select rows in the table and display details of selected rows in Mercury.

Do you think Data Tables will work for you?

Sorry, that it is taking that much time, right now we are working on the next version of Mercury Dashboard that will support easy style customization - set custom logo, navbar color and footer text. Below is preview of coming feature
![image](https://github.com/mljar/mercury/assets/6959032/204e8fc6-74d4-466f-b5a2-030a675070eb)

**Comment by gmouawad** [comment]
> Hi @gmouawad,
> 
> You mean error that port is already in use? It means that you are running some web app at this port. It shouldn't be related.
> 
> I was thinking about your use case ... I remember that you tell me that you are looking for a table that can be used for data display and have search option. I was experimenting with Data Tables js package https://datatables.net/ and I'm thinking about integration of it with Mercury. It has option to search through data in the table. But it is doing search globally on all columns. Do you need search per column?
> 
> Data Tables has option to sort data and display it with pagination. I would love to add option to add option to select rows in the table and display details of selected rows in Mercury.
> 
> Do you think Data Tables will work for you?
> 
> Sorry, that it is taking that much time, right now we are working on the next version of Mercury Dashboard that will support easy style customization - set custom logo, navbar color and footer text. Below is preview of coming feature ![image](https://user-images.githubusercontent.com/6959032/257497268-204e8fc6-74d4-466f-b5a2-030a675070eb.png)

yes exactly that error.

As per the table, yes I need filtering and sorting per column. Filtering Date time column with all the date filtering (in range, older than, newer than etc), text filtering, numeric filtering (bigger than, equals to .. etc) basically this dash ag grid has these features if you like to have a look. 

Locally on my laptop, it is working, but hosting it into the docker container it didn't work and shows the error above

**Comment by pplonski** [comment]
From your description I understand that you copy js file into assets directory when running locally. When running with docker-compose please copy js file to proper directory depending on nginx configuration.

**Comment by gmouawad** [comment]
> From your description I understand that you copy js file into assets directory when running locally. When running with docker-compose please copy js file to proper directory depending on nginx configuration.

yes I have created assets directory under /app/mercury and I have included the js file in assets directory

**Comment by pplonski** [comment]
@gmouawad ok - did you ensure that assests directory is copied to static files in nginx? Please make sure that `assets` directory is copied to `/usr/share/nginx/html` when constructing container for nginx (here is code https://github.com/mljar/mercury/blob/main/docker/nginx/Dockerfile)

**Comment by gmouawad** [comment]
> @gmouawad ok - did you ensure that assests directory is copied to static files in nginx? Please make sure that `assets` directory is copied to `/usr/share/nginx/html` when constructing container for nginx (here is code https://github.com/mljar/mercury/blob/main/docker/nginx/Dockerfile)

Hello,

we have updated the docker file for nginx as below, and still we are not able to have grid working as it should.
![image](https://github.com/mljar/mercury/assets/80507466/ec624489-82a0-4917-9b99-f53942f31562)

**Comment by gmouawad** [comment]
@pplonski a kind reminder

**Comment by pplonski** [comment]
Hi @gmouawad,

I'm very sorry, I don't have time to take a look at it. 

I would recommend to try to use Mercury widgets for filtering and display filtered data in as data frame.

I'm closing the issue, because in the near future we don't have plans to support `dash-ag-grid`.
