### ISSUE TITLE
Float slider

### ISSUE THREAD

**Issue by seang123** [mljar/mercury#335]
Would it be possible to add support for a float slider?
`ipywidgets` already supports a `FloatSlider` object, and updating `/mercury/widgets/slider.py` to use the `ipywidgets.FloatSlider` does appear to work in the jupyter notebook, however the mercurcy notebook no longer updates the slider.

**Comment by aplonska** [comment]
Sure, we will add it in July. @pplonski take a oooo at this. Wysłane z iPhone'aWiadomość napisana przez Sean G ***@***.***> w dniu 14.07.2023, o godz. 15:45:﻿
Would it be possible to add support for a float slider?
ipywidgets already supports a FloatSlider object, and updating /mercury/widgets/slider.py to use the ipywidgets.FloatSlider does appear to work in the jupyter notebook, however the mercurcy notebook no longer updates the slider.

**Comment by pplonski** [comment]
- [x] Code for float slider 
- [ ] code for float range slider
- [ ] update documentation

**Comment by pplonski** [comment]
Changes will be release in version `2.3.2`.
