### ISSUE TITLE
Using mercury with multiple conda environments

### ISSUE THREAD

**Issue by gussabina** [mljar/mercury#336]
Hello:
I 'm getting the "Waiting for worker..." error and following few answers, it seems it might be an installation problem... So I would like to ask how should I install mercury in this case:
I have multiple notebooks working with different conda environments, and I would like to use docker-compose to make those notebooks public (using different ports). What would be the best way to approach this? Should I install mercury in each conda environment and use a different docker-compose.yml for each environment (to change public port)?

Thanks

**Comment by pplonski** [comment]
Hi @gussabina,

Thank you for checking Mercury. From your message I understand that you have two problems.

### 1. Worker is not starting

Could you please provide more details about your issue? Do you get `Waiting for worker` message locally? What operating system are you using? How have you installed Mercury? Could you please start Mercury with verbose flag:
```
mercury run --verbose
```

### 2. Deployment with multiple environments

Mercury Server share the same environment between all notebooks. If you would like to have several different environments, then you should have several deployments of Mercury. Have you managed to deploy single instance of Mercury Server? I would try to do this as a first step. 

The alternative, might be trying our [Mercury Cloud](https://cloud.runmercury.com) - you can easily setup several Mercury Sites with different environments.

**Comment by pplonski** [comment]
Hi @gussabina, I'm closing the issue, please reopen if you still have an issue.
