### ISSUE TITLE
Mercury websocket always in busy

### ISSUE THREAD

**Issue by stroncod** [mljar/mercury#339]
While running `mercury run` locally and I'm getting zero errors in the Django console and this is the output for the javascript console: 
![image](https://github.com/mljar/mercury/assets/7651497/7a912c71-a000-4b96-adc9-abecd0004d52)
 Is there an option to run mercury verbose? My notebook runs fine.

**Comment by pplonski** [comment]
What version are you using?

You can try verbose:
```
mercury run --verbose
```

**Comment by stroncod** [comment]
It works with verbose for some reason. Thanks for the help.
