### ISSUE TITLE
deploying with Docker - update dependencies

### ISSUE THREAD

**Issue by pcornier** [mljar/mercury#340]
I don't know if it needs to be reported but I encountered two errors when I tried to deploy with Docker.
The first one was:

```bash
 > [mercury  7/16] RUN mamba install --yes --file mercury/requirements.txt -c conda-forge:
0.463 Traceback (most recent call last):
0.463   File "/opt/conda/bin/mamba", line 7, in <module>
0.464     from mamba.mamba import main
0.464   File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
0.464     import libmambapy as api
0.464   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
0.464     raise e
0.464   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
0.464     from libmambapy.bindings import *  # noqa: F401,F403
0.464     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
0.464 ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

so I added libarchive13 to the list of dependencies in the Dockerfile.

The second error was:

```bash
7.447 The following package could not be installed
7.447 └─ mercury is installable and it requires
7.447    └─ sqlalchemy 1.4.27  with the potential options
7.447       ├─ sqlalchemy 1.4.27 would require
7.447       │  └─ python >=3.10,<3.11.0a0 , which can be installed;
7.447       ├─ sqlalchemy 1.4.27 would require
7.447       │  └─ python >=3.7,<3.8.0a0 , which can be installed;
7.447       ├─ sqlalchemy 1.4.27 would require
7.447       │  └─ python >=3.8,<3.9.0a0 , which can be installed;
7.447       └─ sqlalchemy 1.4.27 would require
7.447          └─ python >=3.9,<3.10.0a0 , which can be installed.
```

I fixed it by adding python=3.8 to the line:
RUN mamba install --yes python=3.8 mercury -c 

It's all good now 😄

**Comment by pcornier** [comment]
Thank you.

`did you manage to build web app with Mercury?`
It's currently under test but I plan to build a validation app yes.

`Are you happy with it?`
Yes!

**Comment by pplonski** [comment]
May I ask what is your use case?

**Comment by pcornier** [comment]
It's validation of user Excel files using Pandas. The idea is to ask the user to upload Excel files using the file widget and apply validation rules to them, then an error report with charts is presented to the user.

**Comment by XYyanzi** [comment]
I have encountered the similar error too, could you help me to fix it?

`Step 8/17 : RUN mamba install --yes --file mercury/requirements.txt -c conda-forge
 ---> Running in 02895bc3704f
warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
Looking for: ['django==4.2', 'djangorestframework==3.14.0', 'django-filter==21.1', 'markdown==3.3.6', "celery[version='>=5.1.2']", 'sqlalchemy==1.4.27', 'gevent', "nbconvert[version='>=7.8.0']", 'ipython_genutils', 'pyyaml==6.0', 'django-cors-headers==3.10.1', "ipython[version='>=7.30.1']", "ipykernel[version='>=6.6.0']", "psutil[version='>=5.8.0']", "whitenoise[version='>=5.3.0']", "python-dotenv[version='>=0.19.2']", 'django-drf-filepond==0.4.1', "croniter[version='>=1.3.5']", 'pyppeteer==1.0.2', "channels[version='>=4.0.0']", "websocket-client[version='>=1.4.2']", 'execnb', 'ipywidgets==8.0.3', 'dj-rest-auth==3.0.0', 'boto3==1.26.83', 'cryptography', "pyopenssl[version='>=23.1.1']", "bleach[version='>=6.0.0']"]
Pinned packages:
  - python 3.11.*
Could not solve for environment specs
The following packages are incompatible
└─ sqlalchemy 1.4.27  is installable with the potential options
   ├─ sqlalchemy 1.4.27 would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   ├─ sqlalchemy 1.4.27 would require
   │  └─ python >=3.7,<3.8.0a0 , which can be installed;
   ├─ sqlalchemy 1.4.27 would require
   │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   └─ sqlalchemy 1.4.27 would require
      └─ python >=3.9,<3.10.0a0 , which can be installed.
The command '/bin/sh -c mamba install --yes --file mercury/requirements.txt -c conda-forge' returned a non-zero code: 1`

**Comment by pplonski** [comment]
Please try to use Python 3.9

**Comment by XYyanzi** [comment]
It works, Thank you very much

**Comment by pplonski** [comment]
Fixed, thanks to @pcornier!
