### ISSUE TITLE
Convert google colab forms to mercury's framwork syntax

### ISSUE THREAD

**Issue by churnikov** [mljar/mercury#344]
Hi!

I suggest implementing converter from google colab's syntax of forms to mercury.

Example of really popular notebook in lifescience https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb

In my opinion, community would benefit a lot from this, as it would allow running colab notebooks without converting their forms to any other frameworks. This would allow a convenience of running these apps as notebooks on premise with little to no coding.

**Comment by churnikov** [comment]
I would like to try to work on this issue.

**Comment by pplonski** [comment]
Hi @churnikov,

I like the idea. Not sure if this should be part of Mercury. It can be solved with some external script that parse Google Colab widgets syntax into Mercury Widgets API.

I'm closing the issue for now. If anyone will need this feature, please just reopen and upvote the issue. Then I will think about integrating it into Mercury.

Thank you!

**Comment by churnikov** [comment]
Yes, I agree with you.

I'm working on it right now :)
