### ISSUE TITLE
Long running tasks

### ISSUE THREAD

**Issue by SergeyKudrenko** [mljar/mercury#349]
Hi!

Could you please advise how to deal with long running tasks (10+ minutes)?
Currently I face an issue with notebook run gets interrupted after 5 minute of execution. 
According to the logs the worker is marked as Stale and the whole thing restarts after that.

Thanks in advance!

ENV:
OS: macOS Ventura 13.5.1
Python: 3.11
mercury==2.3.1
celery==5.3.1
gevent==23.7.0
ipykernel==6.25.1
ipython==8.14.0

Please find some logs preceding the restart below:
> NB 2023-08-23 14:39:35,254 HTTP Request: POST https://******** "HTTP/1.1 200 OK"
NB 2023-08-23 14:39:35,254 receive_response_body.started request=<Request [b'POST']>
NB 2023-08-23 14:39:35,254 receive_response_body.complete
NB 2023-08-23 14:39:35,254 response_closed.started
NB 2023-08-23 14:39:35,254 response_closed.complete
NB 2023-08-23 14:39:35,255 send_request_headers.started request=<Request [b'POST']>
NB 2023-08-23 14:39:35,255 send_request_headers.complete
NB 2023-08-23 14:39:35,255 send_request_body.started request=<Request [b'POST']>
NB 2023-08-23 14:39:35,255 send_request_body.complete
NB 2023-08-23 14:39:35,255 receive_response_headers.started request=<Request [b'POST']>
NB 2023-08-23 14:39:35,512 Sending ping
NB 2023-08-23 14:39:35,514 WS on_pong
NB 2023-08-23 14:39:35,517 Starting new HTTP connection (1): 127.0.0.1:8000
DJ INFO 2023-08-23 14:39:35,527 runserver HTTP GET /api/v1/worker/d0ccf216-eb30-4213-81ca-4d980ce1990d/162/1/is-worker-stale 200 [0.01, 127.0.0.1:56370]
NB 2023-08-23 14:39:35,527 http://127.0.0.1:8000 "GET /api/v1/worker/d0ccf216-eb30-4213-81ca-4d980ce1990d/162/1/is-worker-stale HTTP/1.1" 200 17
NB 2023-08-23 14:39:35,528 Check worker id=162 is stale True
NB 2023-08-23 14:39:35,528 Delete worker id=162
NB 2023-08-23 14:39:35,529 Starting new HTTP connection (1): 127.0.0.1:8000
DJ INFO 2023-08-23 14:39:35,542 runserver HTTP POST /api/v1/worker/d0ccf216-eb30-4213-81ca-4d980ce1990d/162/1/delete-worker 204 [0.01, 127.0.0.1:56371]
NB 2023-08-23 14:39:35,543 http://127.0.0.1:8000 "POST /api/v1/worker/d0ccf216-eb30-4213-81ca-4d980ce1990d/162/1/delete-worker HTTP/1.1" 204 0
NB 2023-08-23 14:39:35,543 Worker id=162 is stale, quit
NB 2023-08-23 14:39:35,543 WS on_error, 1
NB 2023-08-23 14:39:35,544 Delete Worker output directory: /Users/sergey/Library/Caches/pypoetry/virtualenvs/fuzzy-test-yBClHHd6-py3.11/lib/python3.11/site-packages/mercury/media/d0ccf216-eb30-4213-81ca-4d980ce1990d
DJ INFO 2023-08-23 14:39:35,544 runserver WebSocket DISCONNECT /ws/worker/1/d0ccf216-eb30-4213-81ca-4d980ce1990d/162/ [127.0.0.1:56213]

**Comment by pplonski** [comment]
Hi @SergeyKudrenko,
When running Mercury locally there should be 24 hours timeout. This might be a bug. Do you set `MERCURY_CLOUD` env variable?

Here is a code that returns the max idle time https://github.com/mljar/mercury/blob/7f9c63cbcd461da38f5cb0e0813bd93241020f4c/mercury/apps/accounts/views/utils.py#L15-L27

**Comment by SergeyKudrenko** [comment]
Thanks for your swift response,
is_cloud_version  returns False
and get_idle_time  returns 86400

I will try to prepare a test-case so you can reproduce this behaviour.

**Comment by SergeyKudrenko** [comment]
seems to be a browser issue, don't know how to fix it though
