### ISSUE TITLE
Can not initialize site on Mercury Cloud

### ISSUE THREAD

**Issue by thanapoom-nisamaneewong** [mljar/mercury#359]
"Can not initialize site" , I found this error after uploading files. Does anyone know How to solve it?

**Comment by pplonski** [comment]
Hi @thanapoom-nisamaneewong,

Thanks for reporting the issue. Are you running Mercury locally? Could you please provide output logs from running Mercury in verbose mode:

```
mercury run --verbose
```

What operating system are you using and which Python version?

**Comment by thanapoom-nisamaneewong** [comment]
@pplonski 
On cloud, **https://cloud.runmercury.com/sites**.

**Comment by pplonski** [comment]
Thanks for information. I will look into it.

Did you manage to create a web app locally?

**Comment by pplonski** [comment]
I've  fixed the problem with Mercury Cloud servers - didnt expect such load. Should be fine now ... in case problems, please let me know.

**Comment by thanapoom-nisamaneewong** [comment]
@pplonski  it works, thank you so much.
