### ISSUE TITLE
Change footer 

### ISSUE THREAD

**Issue by wentzlau** [mljar/mercury#362]
I don't think it is right to have the copyright text "Mercury © MLJAR" at the bottom of the screen. It looks like it is MLJAR that holds the copyright to the data and content being presented and that is not the case.

It would be better if it was possible to set copyright text in app settings, to reflect the right copyright rights.

The link to Mercury on Github should be changed to "Powered by Mercury" as it signals that this is the technology behind web application.

It would be great to have the possibility to add a "privacy text" and "terms of service text" in the same way as the Mercury cloud admin page has. That could be located in two markdown files, privacy.md and tos.md if they exists create a link in the footer and popup the text if clicked.

**Comment by pplonski** [comment]
Hi @wentzlau!

Thanks for feedback. I like the idea of providing `privacy.md` and `tos.md`. We need to discuss it with @aplonska.

**Comment by aplonska** [comment]
Thanks for your feedback. We will definitely change the text at the bottom of the screen to "Powered by Mercury". 
The privacy policy and the terms of service in the near future - will be on the task waiting list.

**Comment by AshifulBhuiyan** [comment]
In addition, the page title is not currently easily customizable. It always shows "Mercury - Turn Jupyter ..."
