### ISSUE TITLE
Change header

### ISSUE THREAD

**Issue by wentzlau** [mljar/mercury#363]
It would be great if the application title is shown in header, not Mercury. No offense Mercury is great, but it confuses users of the application.

Also it should be possible to set a header image.

And support for favicon.

**Comment by pplonski** [comment]
Thank you @wentzlau for your feedback. We offer commercial license for users who would like to apply custom styles and logos. I understand your point, we would like to make Mercury sustainable.

**Comment by wentzlau** [comment]
I think that you should differentiate your paid plans on normal hosting parameters not on functionality. Number of applications, file size, worker speed (cpu/mem), cpu hours, custom domain names, authentication are normal hosting parameters.

Styling and customization is part of the normal development process. It will degrade the developer experience when applying styling changes to plots and the site as a whole without being able to see the full result locally.

People who choose to use Mercury do it because they want to share there notebooks fast and easily and are already primed for your cloud solution. Make the development and deployment process easy and fast and you will get a lot of customers.  

If you place styling and other functionality outside the open source project you will not gain from the collaboration with others on these parts.
