### ISSUE TITLE
Import module error

### ISSUE THREAD

**Issue by jl-calda** [mljar/mercury#370]
Would like some clarity about the following.

Below is my file structure
![Screenshot 2023-10-07 at 12 31 04 PM](https://github.com/mljar/mercury/assets/102973841/e9ca00dc-055a-4d5c-959b-21e7ea3a3bf7)

It is working 
![Screenshot 2023-10-07 at 12 31 55 PM](https://github.com/mljar/mercury/assets/102973841/3b958ad1-fa27-49ac-9cc3-1e55ef5752e1)
on VSCode

But when running mercury it can't find my constants import

<img width="1225" alt="Screenshot 2023-10-07 at 12 30 28 PM" src="https://github.com/mljar/mercury/assets/102973841/297b90a4-cfa7-4bea-84c9-02a1f28ed16d">

Thanks

**Comment by pplonski** [comment]
Hi @jl-calda,

Please try to add to notebook

```
import sys
print(sys.path)
```

Do you have the same output in vs code and mercury?

**Comment by jl-calda** [comment]
Hi @pplonski 

They are not same as shown below.

From Mercury

['/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury/apps/..', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury/apps/..', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury/apps/nbworker', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python310.zip', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/lib-dynload', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages']


From VS Code
['/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury', '/Users/jlcalda/Documents/jupyter notebooks/mercury', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python310.zip', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/lib-dynload', '', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages']

**Comment by pplonski** [comment]
Please add missing path to sys.path before importing module. Example:

```python
import sys
sys.path.append("path_to_my_module")

import my_module

```

**Comment by jl-calda** [comment]
Thanks read how python read import. Figured it out now.

**Comment by Yugal0** [comment]
> Hi @jl-calda,
> 
> Please try to add to notebook
> 
> ```
> import sys
> print(sys.path)
> ```
> 
> Do you have the same output in vs code and mercury?

What does it mean to run this in mercury?

**Comment by pplonski** [comment]
It is just to check your paths in the notebook in Mercury.

**Comment by Yugal0** [comment]
> Sure, user has problem with module import, and I suggested to check imported packages by printing `sys.path`. Do you have problem with package import in Mercury notebook? What is your issue? Maybe it will be good idea to create new github issue?

I can't understand what mercury notebook means? and how do I write code there. As of now I only see a webapp open by mercury.

**Comment by pplonski** [comment]
The mercury notebook is a notebook opened by mercury. It is a web app. You need to develop notebook in Jupyter Lab. If you have Python notebook ready, then you can serve it as web app.

**Comment by Yugal0** [comment]
> Hi @pplonski
> 
> They are not same as shown below.
> 
> From Mercury
> 
> ['/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury/apps/..', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury/apps/..', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury/apps/nbworker', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python310.zip', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/lib-dynload', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages']
> 
> From VS Code ['/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages/mercury', '/Users/jlcalda/Documents/jupyter notebooks/mercury', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python310.zip', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/lib-dynload', '', '/Users/jlcalda/Documents/jupyter notebooks/.conda/lib/python3.10/site-packages']

Then how do I get this output from mercury, I can get this from VScode (jupyter in VScode) already
