### ISSUE TITLE
call to websocket keeps pending in mercury development server

### ISSUE THREAD

**Issue by robert-elles** [mljar/mercury#386]
Hi,
I execute `mercury run` from a folder containing some notebook files. Mercury start without any error. It opens the browser listing the notebooks from the folder. I select a notebook and it opens. So far so good.

But now the right side stays grayed out and shows 3 dots indicating that it is loading. With the network tab open I can see that the call to webserver backend keeps pending and never returns. The hanging call originated from Provider.tsx:205 making a request to ws://127.0.0.1:8000/ws/client/1/b67c9541-15....

Firewall is disabled. 

Any ideas to why this is and how to fix or further debug?

Thanks,
Robert

**Comment by pplonski** [comment]
Hmmm, please try to run mercury in verbose mode and attach logs to the issue:
```
mercury run --verbose
```

**Comment by robert-elles** [comment]
Thanks that help. With that I saw another exception. I had made changes in settings.py to point MEDIA_ROOT to another location. Inspection the exception that the same setting exists under app/utils.py.
Maybe errors should be logged to stdout by default an not only when you define --verbose?
