### ISSUE TITLE
Can't display yfile jupyter graphs

### ISSUE THREAD

**Issue by chua0332** [mljar/mercury#392]
Hi,

I am having some issues displaying yfile graph visuals on mercury. It was working a few days back - but now it is just showing this. I tested in my jupyter notebook, everything works fine there. Does mercury not support the visual display? but a few days back the image was rendered which is odd.

<img width="977" alt="Screenshot 2023-10-31 at 12 13 17 PM" src="https://github.com/mljar/mercury/assets/35265821/0e385167-6105-434e-859a-1e424ae9d980">

The visual in my notebook here:

<img width="1101" alt="Screenshot 2023-10-31 at 12 15 10 PM" src="https://github.com/mljar/mercury/assets/35265821/fe6e4c85-3cf7-4d54-8211-49c1cfae64aa">

Thanks,
Eugene

**Comment by pplonski** [comment]
Hi @chua0332,

Thank you for reporting the issue. We would like to add support for all ipywidgets, then it should be working fine in Mercury. However, it is hard to understand, why it was working few days ago?

**Comment by chua0332** [comment]
hi @pplonski ,

Thanks for your quick reply - oddly I was using the old mercury version, the one with mljar-mercury. It worked till late last night, then I realized i was using an obsolete package, I deleted my old working environment this morning and recreated a new working enviroment with this updated package. Then it broke down.. let me see if I can replicate my old work.

so back to what you are saying - not all all ipywidgets are supported by mercury now?

**Comment by pplonski** [comment]
Yes, not all ipywidgets works in mercury now. We would like to change it ...

May I ask what are you building?

**Comment by chua0332** [comment]
Hey @pplonski, i was just trying to build a network graph visual directly from my neo4j cypher query. There would be some parameter injections into the query using the interactive widgets and the graph should be changing to what the end user selected.

But anyway, I checked for the same issue at yfile's github and it seems that the issue cannot be fixed by them too..

<img width="1040" alt="Screenshot 2023-11-01 at 9 38 06 AM" src="https://github.com/mljar/mercury/assets/35265821/6796b8e4-d7a0-4ef2-99f4-2d6d39317ce1">

I guess I would have to close this issue for now. 
Thanks,
Eugene

**Comment by pplonski** [comment]
OK @chua0332, let's close the issue for now. In the case of any further questions we are happy to help.
