### ISSUE TITLE
[feature] Adding a Markdown static widget as "input" widget

### ISSUE THREAD

**Issue by GustavoPeredo** [mljar/mercury#397]
It might be wanted to decorate the Mercury sidebar to improve legibility. Below is an example of a notebook I'm writing to better visualize Linear Algebra:

![image](https://github.com/mljar/mercury/assets/30641461/45e0cef4-ea3e-4685-8711-43b911b5b898)

The proposal regards adding a markdown widget that would render in the sidebar, allowing this:

![image](https://github.com/mljar/mercury/assets/30641461/b99baf54-54cc-4c75-9c92-d97b63a0f3be)

Would it align with the project's design to create such new widget? Should I create a pull request when done? 

What would be the best way for me to achieve this functionality?

**Comment by pplonski** [comment]
Hi @GustavoPeredo,

Please try `Note` widget, here is docs https://runmercury.com/docs/input-widgets/note/
