### ISSUE TITLE
When run the mercury app  'utf-8' codec can't decode byte error appears

### ISSUE THREAD

**Issue by danquio194** [mljar/mercury#400]
Hi! I just installed Mercury and making the test of how it works I'm getting the same error of 'utf-8' codec can't decode byte. The notebooks that I using is just the guide you've provided in the [Create App](https://runmercury.com/tutorials/web-app-python-jupyter-notebook/) page. Actually I only let in my notebook the following cells trying to identify if it was something with my code.

`import mercury as mr`

`app = mr.App(title="App test", description="Testing the Mercury app creation")`

`color = mr.Select(label="Select color", value="blue", choices=["red", "green", "blue"])`

If I run the notebook in Jupyter works well. The problem is when I run it with local server. Someone can help me with that? I didn't find anything related in forums, videos, previous problems or in the documentation.

Thanks a lot in advance!

**Comment by pplonski** [comment]
Hi @danquio194,

Thank you for reporting the issue. What version of Mercury are you using? It is displayed when you start local server with `mercury run` command.

What operating system are you using and what is Python version?

**Comment by danquio194** [comment]
Hi @pplonski  thanks for your quick response.

This is what shows me when run mercury. 
![image](https://github.com/mljar/mercury/assets/82115444/8a7307a1-ffdd-44cd-a272-8c84c1c99e92)

But I set everything within an environment in conda. The python version is 3.8.18,  mljar-mercury is 1.1.6 and I have Windows 10. Those versions are the ones that works for me. When I tried with a newer version of Python, the Jupyter server crashed, or something happened building the wheels to install mercury.

**Comment by pplonski** [comment]
Hi @danquio194,

Could you please try to update mercury with:

```
pip install mercury
```

We changed a lot since version 1, there was a package name change as well. New documentation is at https://runmercury.com/docs

**Comment by danquio194** [comment]
You're right @pplonski . The problem was the mercury version. I don't know why was installed the older version in the env. But thank you, now the notebooks are working pretty well. I take the opportunity to thank you for this amazing app. I think that will be very useful in my job and personal projects :D
