### ISSUE TITLE
Not load data at start

### ISSUE THREAD

**Issue by Kokerboom** [mljar/mercury#403]
Is there any clever workaround how we can prevent notebook from running on start? Like extra button. Putting everything in if would complicate code.

**Comment by pplonski** [comment]
What about adding a [`Stop`](https://runmercury.com/docs/output-widgets/stop/) and the beginning and some [`CheckBox`](https://runmercury.com/docs/input-widgets/checkbox/)

```python
stop_notebook = mr.Checkbox(value=True, label="Switch me")
if stop_notebook.value:
    mr.Stop()
```

It will let you proceed only if you switch checkbox. What do you think?

**Comment by Kokerboom** [comment]
For me - prefect! 
Thanks for help and interesting presentation at DSS.
