### ISSUE TITLE
How to hide the share button?

### ISSUE THREAD

**Issue by italanchan** [mljar/mercury#406]
How to hide the share button?

**Comment by pplonski** [comment]
Hi, there is not such option yet. We can add it. We have option to hide download button https://runmercury.com/docs/input-widgets/app/

**Comment by pplonski** [comment]
@apjanusz it will be great if we can implement this feature in this month

**Comment by pplonski** [comment]
Added `allow_share` parameter in `App()` constructor https://runmercury.com/docs/input-widgets/app/

I'm doing a release of new version in a moment ...
