### ISSUE TITLE
Dynamic parameter configuration

### ISSUE THREAD

**Issue by shivendra2015iiit** [mljar/mercury#41]
If we can add one preprocess block on top that runs only one time when notebooks is added. In this we can get some values which can be used to set configurations of parameter.

An example.

suppose we want to make "select" with choices as name of files in folder we can do something like this.

![image](https://user-images.githubusercontent.com/19734489/153516712-708085bf-d313-4d7c-9c48-0aa26875eba5.png)

**Comment by pplonski** [comment]
Thank you @shivendra2015iiit for the idea. I need to think about it. Please give me some time.

At first sight, it will not work with the current architecture (all widgets values must be set before adding to Mercury). But this might be super useful for users - so let me think about this.

**Comment by pplonski** [comment]
It is implemented in Mercury V2, please read more on https://RunMercury.com
