### ISSUE TITLE
Can't start mercury local server.

### ISSUE THREAD

**Issue by Yugal0** [mljar/mercury#411]
I have just started to learn mercury. While following the webapp making tutorial on the official website [https://runmercury.com/tutorials/web-app-python-jupyter-notebook/](url) , I installed mercury through  pip, it got installed successfully, I can import and use it in my jupyter notebook. But running 
`mercury run`

to start a local server, gives following error-
![image](https://github.com/mljar/mercury/assets/122299659/9aeded16-ef78-47d8-8112-8f37efb4e0b2)

I am running this command in the same directory where my jupyter file is.

Seems like there is some problem in the installation. (I have windows 11)
Please Help!

**Comment by Yugal0** [comment]
I got the solution, mercury was installed, but we need to tell windows where the executable for it is located. 
I just added the location of the scripts folder (which contain the executable for mercury) for my python installation, to the path environment variable in windows.

**Comment by pplonski** [comment]
Great to hear @Yugal0 that you solved the issue! What would you like to build with Mercury? In case of any questions, I'm happy to help!

**Comment by Yugal0** [comment]
Hello @pplonski, Thanks for your response. I already have a code written in a jupyter file, where I do some fitting of data obtained from some lab experiments. I wanted to make that jupyter file more interactive, like the user shouldn't need to scroll up and down always, when they use the file.Then after some internet search I found mercury, it seems like what I need is there. 

Now I only have one doubt, once I complete designing the interface, can I freely host the mercury made web app somewhere.? I know I can always run it offline. But from the point of view of users, it will be a little unwanted annoyance, to have to run some commands each time they want to use my app.

Thanks Again,

**Comment by pplonski** [comment]
Looks like perfect use case for Mercury :rocket: 

Yes, you can host it on your own machine with docker-compose https://runmercury.com/docs/docker-compose/ or you can use our cloud (we have free tier) https://cloud.runmercury.com
