### ISSUE TITLE
Option to hide the RunMercury switch at the top black bar

### ISSUE THREAD

**Issue by gregcode123** [mljar/mercury#417]
Hello:

I have been testing this product and it's wonderful... Only issues I had are with:
- Share button: in some cases, I would prefer not to have our users sharing the links for security reasons.
- The RunMercury switch at the top blank bar, might not be good in those cases where you don't want the users to check all available notebooks, so it would be good to have an option to hide/show this.

Are there these options considered in this product's roadmap?

Regards;
Greg

**Comment by pplonski** [comment]
Hi @gregcode123,

Thanks! We can add option to control share button visibility. Regarding top bar, you can try to embed the app https://runmercury.com/docs/jupyter-notebook-embedding/ then top bar is hidden. Or we might think about making this configurable as well ...

**Comment by pplonski** [comment]
Share button visibility will be implemented in https://github.com/mljar/mercury/issues/406
