### ISSUE TITLE
If the notebook is in sub folder the mercury will not accept it as valid app

### ISSUE THREAD

**Issue by kingabzpro** [mljar/mercury#42]
![image](https://user-images.githubusercontent.com/36753484/153706302-ada0c874-098a-4ef4-8991-c4121883f988.png)

**Comment by kingabzpro** [comment]
If I have three notebooks why it's saying I have 4 in the app?
![image](https://user-images.githubusercontent.com/36753484/153706413-ab587bbd-72ff-4734-a9a6-3e0797017d15.png)

**Comment by pplonski** [comment]
Hi @kingabzpro,

There are two issues that you reported:
1. Problem with add notebook from sub folder. Have you manage to solve it? You should be able to add notebook from any path by specyfing the path to it. 
2. The issue with duplicates. Do you still have issue with duplicates? Can you provide steps to reproduce?

**Comment by kingabzpro** [comment]
For the path, I think it should automatically pick the notebooks for the root directory. If its in the folder then it should tread it as a category. Let say, I have NLP web apps and its in the NLP folders, the app should consider folder as category.

**Comment by pplonski** [comment]
@kingabzpro I was able to run Mercury on Deepnote  but I can't add a notebook to the Mercury - Deepnote doesnt support RAW cells. I was thinking about adding an option to define the YAML in the code cell as a comment https://github.com/mljar/mercury/issues/43 - what do you think?

What do you mean by category? You mean group all notebooks in categories? Just display categories first and then after category is selected display the notebooks?

**Comment by kingabzpro** [comment]
> What do you mean by category? You mean group all notebooks in categories? Just display categories first and then after category is selected display the notebooks?

Yes, but grouping various notebooks into multiple categories. 
![image](https://user-images.githubusercontent.com/36753484/153708486-25f5ccf7-952b-45ce-b21d-3eceed399e8e.png)

I am not sure #43, will improve the usability or not. But we can give a try. I do every thing in the cloud, so if it is cloud friendly, then I am in.

**Comment by kingabzpro** [comment]
I will try it later. I really like this project and I will wait for the cloud version where people can create profile and upload notebook as an app.

**Comment by pplonski** [comment]
@kingabzpro we don't plan to provide the cloud version. I would like to see Mercury as a self-hosted solution. 

But we are open, if there will be many requests for cloud version then we will consider it.

**Comment by kingabzpro** [comment]
Got it.

**Comment by kingabzpro** [comment]
The folder issue is resolved:
![image](https://user-images.githubusercontent.com/36753484/153749729-003797e1-b99f-47f7-8eb0-445c08dec027.png)

Thank you. But i still see extra file that I don't understand. Why is it there on first place?

**Comment by pplonski** [comment]
@kingabzpro it is hard to say, looks like some notebook without a YAML header that was accidentally added to Mercury.

You can remove the notebook with the command:

```
mercury delete notebook_path.ipynb
```

or you can remove it from Admin Panel. If you never used Admin Panel you need to create an admin user:

```
mercury createsuperuser
```

During creation, you can give the fake email address (it is not used anyway). After admin user creation you can log in to Admin Panel by going to `127.0.0.1:8000/admin`. You need to log in with admin credentials. You will have access to the CMS (Content Management System) automatically generated by Django. You can select notebook there and delete.
