### ISSUE TITLE
image from Jupyter notebook not showing

### ISSUE THREAD

**Issue by eustejl** [mljar/mercury#424]
Hello! It seems that images are not rendered in Mercury, which is also the case when I export them to pdf. I added the image to the Jupyter notebook using img src=... I am running Mercury in my local device.

Is there a way to solve this? Thanks!

![image](https://github.com/mljar/mercury/assets/83872920/c7b5d1c6-0b25-4f40-90eb-99ae3ace8d45)

**Comment by pplonski** [comment]
Please try to upload image for example to GitHub repository and then use external url to display image.

The other way might be to encode it to base64. Please check possible ways in my [article about displaying images in notebook](https://mljar.com/blog/jupyter-notebook-insert-image/). 

Please let me know if it works for you.

**Comment by eustejl** [comment]
I dragged and dropped the images to the markdown cell, and it worked perfectly. Thank you!
