### ISSUE TITLE
allow to define YAML prams as comment with """ or '''

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#43]

**Comment by kingabzpro** [comment]
Running app in Deepnote give error. do I need to convert the cell type?
 
![image](https://user-images.githubusercontent.com/36753484/153749883-76d9a5ef-b739-4a63-8c76-c1dcbf68f809.png)

**Comment by pplonski** [comment]
Yes, the YAML header should be in the RAW cell. I don't know if Deepnote supports RAW cells?

**Comment by kingabzpro** [comment]
No, It dosent. Well. Let me ask the developers.

**Comment by pplonski** [comment]
no YAML in V2 ... Please read more on https://RunMercury.com
