### ISSUE TITLE
Problem Installing with PyYaml=6.0

### ISSUE THREAD

**Issue by cbitterfield** [mljar/mercury#431]
This package does not install on Win 11 or OSX Sonoma.
Recommend changing requirements.txt to 

pyyaml=6.0.1

that will install.

**Comment by pplonski** [comment]
Thank you @cbitterfield for information. I've removed `pyyaml` dependency. We were using it in previous version and now it is not used at all.

Have you been able to build web app with Mercury? What is your use case?
