### ISSUE TITLE
Option to hide specific cells/output 

### ISSUE THREAD

**Issue by informatica92** [mljar/mercury#438]
Hello, 
I am quite new with Mercury but, looking at it at first stage, trying to convert my very long notebooks into something shareable, I noticed that there is no way to hide some specific cells from the resulting webapp.

I mean, usually, in my notebooks I have some intermediate outputs between the ideal input and the final output.

Is there a way to hide some cells that I do not want to be rendered by mercury? 

Like nbconver does, can we assign a custom tag to each of the cell we want to hide and then instruct mercury to skip rendering those specif ones? 
SOURCE: https://stackoverflow.com/questions/49907455/hide-code-when-exporting-jupyter-notebook-to-html

**Comment by pplonski** [comment]
Hi @informatica92,

Right now there is no such option. You can add Checkbox to control display of intermediate outputs. Here is docs https://runmercury.com/docs/input-widgets/checkbox/
