### ISSUE TITLE
Is is possible to get login user name

### ISSUE THREAD

**Issue by zenz** [mljar/mercury#459]
As subject.

If then, we can use to provide some specified contents to the login user.

**Comment by pplonski** [comment]
Hi @zenz,

the title is cut, I guess you are asking how to get information about logged user? There is `user()` function in mercury that return information about logged user.

```python
import mercury as mr

u = mr.user()
print(u)
# if user is logged you should get dict with username and email, otherwise empty dict
> {"username": "zenz", "email": "zenz@email.com"}
```

**Comment by zenz** [comment]
> Hi @zenz,
> 
> the title is cut, I guess you are asking how to get information about logged user? There is `user()` function in mercury that return information about logged user.
> 
> ```python
> import mercury as mr
> 
> u = mr.user()
> print(u)
> # if user is logged you should get dict with username and email, otherwise empty dict
> > {"username": "zenz", "email": "zenz@email.com"}
> ```

Yes, that what I mean. I will give it a try. Thank you!
