### ISSUE TITLE
How can we clear cached contents on notebook list page?

### ISSUE THREAD

**Issue by zenz** [mljar/mercury#460]
as title.
I want to hide contents on list page, but mercury aways shows the cached content.

**Comment by pplonski** [comment]
Please try to run command 

```
mercury run clear
```

it will delete local database. When you will start mercury again the new database will be created. Please take a look for mercury commands in the docs https://runmercury.com/docs/commands/

**Comment by zenz** [comment]
> Please try to run command
> 
> ```
> mercury run clear
> ```
> 
> it will delete local database. When you will start mercury again the new database will be created. Please take a look for mercury commands in the docs https://runmercury.com/docs/commands/

Sorry, this is not a good solution for my condition.

I'm running mercury on a linux server. without X or any browser can work in terminal support javascript. So I can't use mercury run clear to clean the cache.

**Comment by pplonski** [comment]
Please try to login to Admin Panel and delete unwanted notebooks
