### ISSUE TITLE
using spotipy package in runmercury.com

### ISSUE THREAD

**Issue by Tlo-l-w** [mljar/mercury#461]
Keep facing this issue and can't seem to fix it in any way. Had a similar issue with requests that just needed a different version of urllib, but this one has no hints to what could be wrong. Please let m know!

<img width="1017" alt="Screen Shot 2024-08-03 at 7 32 59 PM" src="https://github.com/user-attachments/assets/56ee06bd-14b7-4040-a7e6-7f495a711aab">

**Comment by pplonski** [comment]
Maybe it is connected with Python version? Cloud is still using Python 3.8. Is it working locally on your machine? What Python version are you using?
