### ISSUE TITLE
add ability to change the PORT for mercury watch command

### ISSUE THREAD

**Issue by mckeown12** [mljar/mercury#51]
As of `0.5.1` there is no way to change the port for mercury when using `watch`.  There are various work arounds using `runserver` and [something external](https://calmcode.io/entr/introduction.html) to control restarts, but this would be a nice convenience. 
#50

**Comment by pplonski** [comment]
No more `watch` command in Mercury V2. Just run `mercury run` in the directory with notebooks. Please read more on https://RunMercury.com
