### ISSUE TITLE
Accept HOST or add to the list of hosts via a configuration file

### ISSUE THREAD

**Issue by MarvinKweyu** [mljar/mercury#55]
Could there be a way to read a `config` file for the application run? Essentially a `.env` file or other configuration for ports and so forth.

**Comment by pplonski** [comment]
Hi @MarvinKweyu,

Some of the variables are loaded from `.env`, for example, `ALLOWED_HOSTS`. We are using `python-dotenv` package. 

Which variable would you like to set?

**Comment by MarvinKweyu** [comment]
Could this detail be included in the documentation? Could not get it at first, so I went on a figure it out spree. 

None the less, I know the project is still in progress on digital ocean deployment. As a heads up, I attempted it , but this would fail to load the notebook detail. I 'll leave this for the next update of the same.

**Comment by pplonski** [comment]
@MarvinKweyu sorry! I will add this to docs.

How are you trying to deploy it to Digital Ocean? The steps should be very similar to [AWC EC2 deployment](https://github.com/mljar/mercury/wiki/Deploy-to-AWS-EC2) with docker-compose.

**Comment by MarvinKweyu** [comment]
Ahh...I see. I Used the **app platform** but would very much like to use the droplet instead. I tested this locally and encountered a few setbacks. This specific issue #55 being tagged docs on virtual environment configuration, should this description be here or be on a separate thread?
