### ISSUE TITLE
Reading notebook without utf-8 encoding

### ISSUE THREAD

**Issue by doubianimehdi** [mljar/mercury#58]
Hi,

Thank you for your amazing work !

I have a problem when I try to convert my notebook with mercury run, I have the following message : 
Error during notebook initialization. 'charmap' codec can't decode byte 0x9d in position 3522922: character maps to <undefined>

the notebook runs fine in jupyter and I have no issues ... I can't understand from where it can come from ...

Please help !

Thank you in advance.

Best Regards

**Comment by pplonski** [comment]
Hi @doubianimehdi,

Thank you!

Could you please attach a notebook to this issue or send me by email to contact@mljar.com? Without an input notebook, it is hard to reproduce the issue (I've never seen such before). This might be some bug in the framework.

**Comment by doubianimehdi** [comment]
> Hi @doubianimehdi,
> 
> Thank you!
> 
> Could you please attach a notebook to this issue or send me by email to [contact@mljar.com](mailto:contact@mljar.com)? Without an input notebook, it is hard to reproduce the issue (I've never seen such before). This might be some bug in the framework.

Hi @pplonski ,

I've sent the notebook by mail ... it seems I have this problem with all my notebooks now ...

**Comment by pplonski** [comment]
Problem running in Mercury or in Jupyter?

**Comment by doubianimehdi** [comment]
Problem running in Mercury, in Jupyter no problem whatsoever ...

**Comment by pplonski** [comment]
Oh, didn't get the email with notebook. Could you please resend it?

**Comment by doubianimehdi** [comment]
Just resent it with 7zip file attached ... Title of the mail is "Problem when converting notebook with run #58"

**Comment by pplonski** [comment]
@doubianimehdi I got some issues with my email service. Please try to resend it to another email support@mljar.com - Sorry for the problems.

How big is the zip package?

**Comment by pplonski** [comment]
@doubianimehdi got your email - it was in spam!

**Comment by pplonski** [comment]
@doubianimehdi I run your project with Mercury on fresh virtualenv without any issues. The command that I've used:

```
mercury run <notebook_name>
```

**Comment by doubianimehdi** [comment]
That's odd ... can you tell what packages you used in your venv ?

**Comment by pplonski** [comment]
I only used `mljar-mercury`.

**Comment by pplonski** [comment]
are you on windows?

**Comment by doubianimehdi** [comment]
Yes I am !

**Comment by pplonski** [comment]
I was testing on Ubuntu. There might be an issue with file encoding. Are you able to change the Mercury code locally?

You will need to try to change this line:
https://github.com/mljar/mercury/blob/68db08d66d9ed90fc86c7b10ac2485f93dfe5885/mercury/apps/notebooks/tasks.py#L103

and change to `with open(notebook_path, encoding="utf-8", errors="ignore") as f` - that's my first guess what can be wrong ...

**Comment by doubianimehdi** [comment]
Ok ! I'll try that ! thanks !

**Comment by pplonski** [comment]
Great! I'm happy that it works for you. Thank you for your help in tracking the issue.

I will reopen the issue and add a fix to the code - other Windows users might have a similar problem.
