### ISSUE TITLE
CJK（Chinese, Japanese, Korean）Character in TextWidget

### ISSUE THREAD

**Issue by faisalron** [mljar/mercury#70]
I am trying to input Japanese characters using the Text Widget, but it constantly disappeared. 
I guess the root cause is the sanitize function in the code below:
https://github.com/mljar/mercury/blob/main/frontend/src/components/Widgets/Text.tsx#L24

Is there any particular reason to remove CJK characters in the TextWidget?

**Comment by pplonski** [comment]
Hi @faisalron,

Thank you for reporting the issue. Sorry about the problem. I wasn't aware of it. It's a bug. I will fix it.

**Comment by pplonski** [comment]
@faisalron it should be fixed. I've released the updated version as `0.6.2`.

**Comment by faisalron** [comment]
@pplonski, thank you for your prompt response. It works perfectly.
