### ISSUE TITLE
clear tasks button not refreshing the UI

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#77]
After clicking `Clear tasks` the UI in the sidebar is not refreshed.

**Comment by pplonski** [comment]
Expected behavior:

![Peek 2022-04-26 10-44](https://user-images.githubusercontent.com/6959032/165260352-20f76ee6-a7c7-492d-b403-62542bc6522d.gif)

**Comment by pplonski** [comment]
Thanks @fitiskin

**Comment by Konsilion** [comment]
Hey @pplonski ,

Why doesn't this reset button exist anymore? ^^'

Thanks again for Mercury, it really helps !
