### ISSUE TITLE
create a demo with vizzu

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#81]
The vizzu is a package for creating animated charts in Jupyter notebook.

Please create a demo app/notebook with vizzu in Mercury.

**Comment by rajeshai** [comment]
Please check this demo visualization I created on the tips dataset using mercury and ipyvizzu. It works fine. It is deployed on hugging face spaces.
[https://huggingface.co/spaces/rajesh1729/animated-visualization-with-mercury-ipyvizzu
](URL)
