### ISSUE TITLE
Sort apps in the mercury gallery

### ISSUE THREAD

**Issue by rajeshai** [mljar/mercury#84]
Hi
Is there a way to sort apps in the gallery based on the title of the notebook or date updated or any other given condition?? Please look at the attached image. It consists of ML notebooks of a course. It has a few apps. I want to sort the apps based on the title so that notebooks will be in order and users can go through them easily. This is the website [link ](https://mlnotebooks.herokuapp.com/) for the app in which I want to sort.

![Capture](https://user-images.githubusercontent.com/73292655/163558267-5e7be847-753c-41cb-9330-bc95f822df47.JPG)

**Comment by pplonski** [comment]
Notebooks are sorted by `slug`. The `slug` is constructed based on their file name, and it is used to construct URL for Mercury App (notebook). You can for example set file names for notebooks:
- `1 first notebook.ipynb`
- `2 second notebok.ipynb`
- ...

and file names will be used in sorting.
