### ISSUE TITLE
Mercury + Gradio colab

### ISSUE THREAD

**Issue by AK391** [mljar/mercury#88]
Hi, I saw the post here https://www.reddit.com/r/MachineLearning/comments/u7t77t/d_running_interactive_python_notebooks_on on using the mercury framework to generate a web app in Hugging Face spaces using the gradio sdk

would be great to explore ways to collaborate with mercury and gradio, https://gradio.app/

**Comment by pplonski** [comment]
Hi @AK391, 

creating Python notebook with analysis and plots can be difficult, sharing it shouldn't be! Let's explore ways to collaborate. I'll email @abidlabs

**Comment by rajeshai** [comment]
HI
Gradio works fine within the mercury. When we upload the saved notebook with gradio already in an executed state, it's running smooth.  We can share jupyter notebooks with gradio implementations using mercury.
check this app deployed on hf spaces - https://huggingface.co/spaces/rajesh1729/mercury-gradio-test

But when we upload a notebook without gradio output and click the run button, there seems to be a port issue on hf spaces..
check this app here https://huggingface.co/spaces/rajesh1729/mercury-gradio-test-1
